### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by MarcoLugo** [amcharts/amcharts3#100]
Hi,

Running only one chart (map, in this case) increases memory usage over time. The increase seems to be exponential, where it is a few hundred kilobytes per second at first and can go to a couple of megabytes per second after a few minutes. Total usage can easily go above a gigabyte after 15 minutes. Disabling the chart on the webpage (roughly the same configuration as the first map demo: https://www.amcharts.com/demos/animations-along-lines/) fixes the problem right away.

I am using AmCharts version 3.20.20 with Chrome version 56.0.2924.87.

Here is a screenshot of the timeline feature of the Chrome developer console on AmCharts' own example (https://www.amcharts.com/demos/animations-along-lines/), for only the first 30 seconds.

![image](https://cloud.githubusercontent.com/assets/6843447/22844488/815a7c14-efac-11e6-9910-a9b484da136c.png)

This is a 10 second timeline about three minutes later:

![image](https://cloud.githubusercontent.com/assets/6843447/22844629/3d31f5de-efad-11e6-94f8-66dca0e5e0fb.png)

**Comment by martynasma** [comment]
Thanks for the heads up.

It looks like it is related to animation.

We are going to look into this and keep you posted.

**Comment by MarcoLugo** [comment]
Thank you so much for looking into it. Meanwhile, and also to test that hypothesis, how would I go about deactivating the animation? I looked into this (http://stackoverflow.com/questions/32122542/amcharts-disabling-animations/32122599), both setting animationDuration to zero or deleting completely and also setting it to null and it did not work for me.

Thank you

**Comment by martynasma** [comment]
Hi there,

We just released version 3.21.0 which should take care of this animation-related memory-leak.

Let me know if you're still having the issue after upgrading.
