### ISSUE TITLE
[NPM] No more available !

### ISSUE THREAD

**Issue by skol-pro** [amcharts/amcharts3#104]
Amcharts3 is no more available on NPM :-(

**Comment by martynasma** [comment]
I'm afraid we never had an official NPM repository.

You can install amcharts3 using npm with github:

```
npm install amcharts/amcharts3
```

**Comment by ryzy** [comment]
Are there any plans to release an official NPM package?

Using github is fine, but having a properly versioned package in NPM registry would be better.

**Comment by martynasma** [comment]
Not at the moment. Sorry.
