### ISSUE TITLE
Multiple Value Axes offset

### ISSUE THREAD

**Issue by Egoryk** [amcharts/amcharts3#109]
I had a problem that can be shown in a demo, the link to which I dropped below. The problem with hiding the graph on the legend and at the same time hiding the axis, but the graph has not been redrawn
https://www.amcharts.com/demos/multiple-value-axes/

![image](https://cloud.githubusercontent.com/assets/6002484/24498256/a2402446-1546-11e7-8a11-d8fc82cd9961.png)

**Comment by martynasma** [comment]
This is happening because the value axes are set using a fixed offset.

I suggest you take a look at our autoOffsetAxis plugin which does that automatically and dynamically:

https://github.com/amcharts/tools/tree/master/autoOffsetAxis

**Comment by Egoryk** [comment]
Thanks you. I altered for myself autoOffsetAxis.zhs and now everything is fine
