### ISSUE TITLE
XSS in chart balloons

### ISSUE THREAD

**Issue by segorov** [amcharts/amcharts3#11]
Hi,

There appears to be an XSS vulnerability in the chart balloon implementation. Tested in Chrome using the latest version of the code from this repository. In this scenario, unsanitized input is passed in as the bubbleText data in the dataSource to a chart. The labels on the X axis show up as expected, but hovering over data points triggers the XSS.
![screen shot 2016-01-05 at 12 25 07 pm](https://cloud.githubusercontent.com/assets/11316935/12122175/70ca2a26-b3a7-11e5-99c4-b55788e6a9c5.png)
Hovering:
![screen shot 2016-01-05 at 12 06 27 pm](https://cloud.githubusercontent.com/assets/11316935/12121990/715262fc-b3a6-11e5-8d01-4bbe663af045.png)

I considered sanitizing the data during chart creation, and that mitigates the XSS but causes double sanitization of the labels:
![screen shot 2016-01-05 at 12 23 25 pm](https://cloud.githubusercontent.com/assets/11316935/12122961/3360a73c-b3ac-11e5-8914-fdc50b646601.png)
Hovering:
![screen shot 2016-01-05 at 12 07 38 pm](https://cloud.githubusercontent.com/assets/11316935/12122965/3a7363de-b3ac-11e5-871d-816bf1f00295.png)

For AmGraph objects, this can be remedied by defining a balloonFunction that sanitizes the input. However, AmChart objects don't have that option. Is there a workaround that can deal with this type of input correctly at both the labels and inside that balloons? Thanks!

**Comment by martynasma** [comment]
Hi there,

I'm not entirely sure it can be considered an XSS vulnerability. There's no way for users to inject something into balloons of the charts that can be seen by other users, unless your service supports input of the information from users for display to other users.

In the latter case, I'm pretty sure sanitation should occur at the moment of the data entry. Or when the charts or data for them are generated on your server.

The balloon contents are full-fledged HTML. A lot of people rely on it to display rich information, like tables, images, etc. Escaping all this would be a step backwards.

I suppose the only option would be to selectively parse balloon contents for any JavaScript code / on* handlers and strip it out. However, that seems like a very complicated solution.

Any other ideas are welcome.

**Comment by segorov** [comment]
Hi,

Thanks for the response. I agree that yes, to cause XSS, a user must be able to influence data displayed to another user and the use case for this may be limited. However, the general problem with sanitizing data like the example above when the charts are generated is that special characters will appear double sanitized in the label as in screenshot 3/4, unless I'm missing a way to change this behavior. Looking through your docs, it seems like it would be simple to remedy this by adding a balloonFunction property to the AmChart object that works just like the same property in the AmGraph object. Is this possible or was there a reason it was intentionally left out of the AmChart implementation?

**Comment by segorov** [comment]
Any more thoughts on this?

**Comment by martynasma** [comment]
I'm sorry, your reply somehow slipped through the cracks.

There is such function for the category axis balloons. It's in the chartCursor and it's called `categoryBalloonFunction`:

http://docs.amcharts.com/3/javascriptcharts/ChartCursor#categoryBalloonFunction

**Comment by segorov** [comment]
That's exactly what I needed. Thanks for looking into it!
