### ISSUE TITLE
Gauge, strongly use a processor and memory on large numbers

### ISSUE THREAD

**Issue by bezdna** [amcharts/amcharts3#112]
Very much used the processor and memory on large numbers, already at a maximum value of 10,000
If you increase by 1 order the browser can hang, RAM more than 1Gb is used
Tested in 57 Chrome on Linux
https://codepen.io/bezdna/pen/eWprLo
http://i.prntscr.com/acc023f08f604c8e925dc93f0f4577ca.png
Can someone tell a good solution with a similar schedule for large numbers?

**Comment by martynasma** [comment]
Since the `valueInterval` is at 1, you have a very high amount of ticks on the value axis between 0 and 10K.

Setting `"valueInterval": 100` and `"labelFrequency": 10` or some similar values should help with the CPU untilization.

**Comment by bezdna** [comment]
thanks, its a good solution
