### ISSUE TITLE
Candlestick graphs cannot be clustered?

### ISSUE THREAD

**Issue by apendua** [amcharts/amcharts3#115]
I am looking to implement the following type of chart:

<img width="516" alt="zrzut ekranu 2017-05-01 o 11 54 49" src="https://cloud.githubusercontent.com/assets/1971195/25577290/37c830b2-2e65-11e7-969c-8d44ccd976fc.png">

but with candlesticks. Unfortunately, it when I switch the type of chart to "candlestick", the graphs always collapse 

<img width="485" alt="zrzut ekranu 2017-05-01 o 11 56 09" src="https://cloud.githubusercontent.com/assets/1971195/25577343/8d21b146-2e65-11e7-8952-360322fb9f93.png">

I tried different configuration options but it looks they just cannot be clustered as the "column" graphs. Is this by design or is it a BUG?

**Comment by martynasma** [comment]
Ho there.

Candlesticks indeed cannot be clustered.

However, looking at your example you don't seem to need candlesticks. Those are floating columns, which CAN be clustered.

https://codepen.io/team/amcharts/pen/9473c25c8e513426de9f78a7b2b727f4

I hope this helps.

**Comment by apendua** [comment]
@martynasma Thanks for answering.

Unfortunately floating columns wound not work for me. Sorry for not expressing myself clearly. The first example was actually rendered with floating columns. What I need in addition to that is that vertical line that is present in candlestick but not in regular columns.

If candlestick cannot be clustered, would it be possible to add that additional line to columns? I know this can be achieved by overlaying graphs, but that's not really an option when I am interested in clustering them, right?

It does not feel like a lot of work, and I would be happy to submit a PR myself but it does not seem feasible as you're only publishing a minified version of the library.

**Comment by martynasma** [comment]
Gotcha.

Unfortunately, there's currently no plans to implement clustered candlestick graphs.

Sorry.

**Comment by apendua** [comment]
@martynasma Can you at least add that statement to the documentation so that other people do not need to waste time on it as I did? Currently, the description of "clustered" setting reads

> In case you want to place this graph's columns in front of other columns, set this to false. In case "true", the columns will be clustered next to each other.

https://docs.amcharts.com/3/javascriptcharts/AmGraph#clustered

I understand from the context that when the author says "graph's columns" he implicitly assumes that it's a column graph. But since there are other types of graphs that also looks like "columns" and also `columnWidth` apparently applies to candlestick as well, it ends up being quite confusing. I think it would be more clear if the documentation included a warning, e.g.

> currently this option (clustering) only works with graphs of type `column`

Does that make sense?

**Comment by martynasma** [comment]
Yes it does makes perfect sense. Thanks for the suggestion!

Just updated the docs.

**Comment by apendua** [comment]
@martynasma Thank you.
