### ISSUE TITLE
connect : false

### ISSUE THREAD

**Issue by nattynatty** [amcharts/amcharts3#12]
I am not sure if connect:false is supposed to work this way as in this fiddle.

https://jsfiddle.net/txofuyhf/1/

I would like the gaps so that if the value for Graph2 is null, no line connector is displayed. I have tried gapField but that did not help. Also the null values are being converted to 0.

A great library, btw.

**Comment by nattynatty** [comment]
Any ideas what I might be doing wrong here.

**Comment by gogglespisano** [comment]
I would look very closely in the debugger to see if the "null" values really are set to null at runtime.  I had the same problem and some JS code was converting them to 0.  It's best if you can just not set the values which are null.

**Comment by nattynatty** [comment]
Thanks @gogglespisano. I checked the original fiddle and there was no null value. I tried a new data set altogether but in this case the second data set is being ignored altogether.

https://jsfiddle.net/a0p3vm8r/1/

I want to display the data from chartData2 set but it does not display at all. Any suggestions?

**Comment by gogglespisano** [comment]
What I did was something like this:  I don't remember if I ever solved he null/0 problem on the stockchart or not.  I eventually went back to using a serialchart rather than the stockchart
    
   if (a1%2 != 0)
   {
   	chartData.push( {
      date: newDate,
      value1: a1
    	} );
    }
else
{
chartData.push( {
      date: newDate,
      value2: a2
    } );
}

**Comment by martynasma** [comment]
Hey everyone. Maybe you'll find this useful. Use `NaN` instead of `null`:

https://jsfiddle.net/txofuyhf/7/
