### ISSUE TITLE
AmBalloon on mobile/Tablet

### ISSUE THREAD

**Issue by anirudhsamudrala** [amcharts/amcharts3#120]
Just curious, does the AmBalloon work with mobile/tablet on hover? I have to make a decision weather or not to keep AmBalloon !

**Comment by martynasma** [comment]
Yes, it does. On touch devices the balloon (if available) is shown on first tap. If object has a click action associated on it, the subsequent tap performs click function.

I hope that makes sense.

**Comment by anirudhsamudrala** [comment]
@martynasma Yes, Thank you!

**Comment by martynasma** [comment]
You're welcome.
