### ISSUE TITLE
Clustered Bar Chart Missing bar width

### ISSUE THREAD

**Issue by hombrew** [amcharts/amcharts3#121]
Hello,

Currently I'm trying to build a Clustered bar chart, following this example,
https://www.amcharts.com/demos/clustered-bar-chart/

Data is displayed as expected, except that, there are some bars info that wont be on all the data points, for example:

```javascript
const chartData = {
  ...,
  dataProvider: [ {
    program: '1383',
    'user-1': 80,
    'user-2': 6
  }, {
    program: '5771',
    'user-3': 5
  } ],
  ...
```
the problem with this is all the unused space, as seen in the following picture:
<img width="913" alt="screen shot 2017-07-10 at 2 28 53 pm" src="https://user-images.githubusercontent.com/11640369/28033605-be524da4-657c-11e7-9cb3-4333d9f86659.png">

I know this is done for maintaining an order between clusters, but I would like columns width to be 0 when their data is undefined. How can I achieve this?

Thanks in advance for any help you can offer.

**Comment by martynasma** [comment]
Hi there,

Unfortunately, there's no way to remove this empty space. The chart will always reserve the space for all available graphs.

Sorry.

**Comment by hombrew** [comment]
oh well, anyways, thanks for taking the time to answer!
