### ISSUE TITLE
Amcharts is never the latest in npm/yarn

### ISSUE THREAD

**Issue by ipa1981** [amcharts/amcharts3#123]
Amcharts always wants to be updated.

```
$ yarn upgrade amcharts3 --dev
yarn upgrade v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ amcharts3@3.21.3
Done in 14.82s.

$ yarn outdated
yarn outdated v0.27.5
Package              Current      Wanted Latest Package Type    URL                                                
amcharts3            3.21.3       exotic exotic devDependencies github:amcharts/amcharts3 
Done in 1.90s.
```

Could it be possible to get a "normal" versioned npm package?

**Comment by tomwayson** [comment]
I wonder if my question is related. I was wondering if there's a reason that the npm package suggests installing from GitHub (`npm install amcharts/amcharts3`).

**Comment by martynasma** [comment]
The `amcharts` package on npm is not officially supported by amCharts. It was created by someone else, we have no relations with.

amCharts currently does not have an official package on npm.

Installing it from Github (via `amcharts/amcharts3`) is the only way to ensure you get the latest version.

**Comment by ipa1981** [comment]
@martynasma AmCharts are installed from GitHub (you may see it it from console output), however that is the point of this issue. Both yarn and npm always shows the amcharts outdated if installed directly this way, which is a bit annoying. 

Is there a reason you do not provide official npm package with correct versioning?

**Comment by martynasma** [comment]
@ipa1981 

> Is there a reason you do not provide official npm package with correct versioning?

That is an excellent question :)

The sole reason is that the names of the packages are already taken.

I'm going to reach out to respective package creators asking to transfer ownership of those packages to us, so that we can keep them up to date.

Will keep you guys posted.

**Comment by ipa1981** [comment]
@martynasma maybe you can use another name until resolved or if no resolution at all? I guess this is better than nothing ;)

**Comment by martynasma** [comment]
Let's give it a few days to resolve. I don't want to create multiple packages and end up users using multiple names.

I'm expecting original creators to collaborate. After all they probably did that so they can use it themselves.

If that does not work out, I'll just use scoped packages i.e. `@amcharts/amcharts3`, but for everyone's sake, I'd love to have those base names. They're more intuitive and consistent with GitHub repos.

**Comment by Jdban** [comment]
Any updates on this? I'm cleaning up my package.json and amcharts is the only one left to clean up :)

**Comment by martynasma** [comment]
@Jdban We're still waiting for the resolution. Owner of "amcharts3" package did not respond to all emails. We're trying to work with the npmjs team, who apparently have policies for that kind of situation in place.

All other amCharts packages (amstock3, ammap3) have been transfered and are being updated by us.

Will keep you guys posted about any changes for "amcharts3".

**Comment by martynasma** [comment]
OK, so `amcharts3` package on npmjs is now officially maintained by amCharts team.

Thanks everyone for hanging in :)

**Comment by sljavi** [comment]
cool, I just send a PR to update the readme 
https://github.com/amcharts/amcharts3/pull/165
fyi @martynasma
