### ISSUE TITLE
Initializing the same chart again breaks its Scrollbar

### ISSUE THREAD

**Issue by Frexuz** [amcharts/amcharts3#124]
## Codepen demo
https://codepen.io/frexuz/pen/mMEzdg?editors=0010

## Errors

> amcharts.js:46 Error: <path> attribute d: Expected number, "MNaN,24.5 LNaN,19…

in

```
setAttr: function(a, b, c) {
    void 0 !== c && a.node.setAttribute(b, c) // ERROR HERE
},
```

## Use case
In my case, I'm using [Turbolinks](https://github.com/turbolinks/turbolinks) for a SPA-like website. This gem is a default one in Ruby on Rails. Navigating to a different page and then navigating to the page with the chart again breaks the chart's scrollbar. Simulated in the Codepen demo.

### Notes
Always works fine on first page load.

Thought it might have something to do with Turbolinks, but it doesn't seem so (again, the Codepen demo has the same behavior)

I did try to remove the charts completely before/after navigating.
```
document.addEventListener('turbolinks:before-render', function(event) {
  var $html = $(event.data.newBody);
  $html.find('.chart-wrapper').html('');
});

document.addEventListener("turbolinks:before-cache", function() {
  $('.chart-wrapper').html('');
});
```

**Comment by martynasma** [comment]
It looks like you are reusing objects for chart config.

Chart uses config object to store it's own objects, states, event handlers and whatnot. When you are trying to reuse those "augmented" settings for another chart, it creates all kinds of anomalies, like the one you are seeing.

So, to be on the safe side, you should always use a "clean" copy of the settings to pass in into `makeChart()`.

Furthermore, before creating a new chart over the old one, make sure you destroy the old instance by calling its [`clear()`](http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#clear) method to free up resources.

I hope that makes sense.

**Comment by Frexuz** [comment]
Using new copies of the settings worked :) Thanks a lot for the fast response.
