### ISSUE TITLE
Remove the middle line between 2 set of columns

### ISSUE THREAD

**Issue by eldyvoon** [amcharts/amcharts3#126]
https://www.amcharts.com/demos/stacked-bar-chart-with-negative-values/

Found this stacked chart but how can I remove the middle grey line on the y-axis? Couldn't find any option for that.

**Comment by martynasma** [comment]
There's a guide added at zero value that draws the zero line. Just remove this code:

```
"guides": [{
   "value": 0,
   "lineAlpha": 0.2
}]
```

https://codepen.io/team/amcharts/pen/108aa157707f73fec1c3c8dfacd0fde8?editors=0010

**Comment by eldyvoon** [comment]
@martynasma  thanks so much!
