### ISSUE TITLE
chart zoom bar growing automatically - Column chart  (JavaScript Charts )

### ISSUE THREAD

**Issue by abdulwahabplus** [amcharts/amcharts3#127]
I been facing some performance issues with the scroll and zoom (in/out) with huge data. it solved by setting `updateOnReleaseOnly = true`.  But after that when I scroll the chart, scrollbar is growing up automatically.

Fiddle : http://jsfiddle.net/abdulwahabplus/6eqe272y/11/

**Comment by martynasma** [comment]
This seems like a bug. Stay tuned for the fix.

Thanks!

**Comment by abdulwahabplus** [comment]
@martynasma Thanks a lot for the reply, BTW when can we expect this fix.

**Comment by martynasma** [comment]
I'm hoping next week.

**Comment by abdulwahabplus** [comment]
Its working fine with the version 3.21.6 (August 30, 2017)

Thanks a lot.
