### ISSUE TITLE
Chart maxSelectedTime property not respected by chartScrollBar

### ISSUE THREAD

**Issue by edclement** [amcharts/amcharts3#13]
We had been using v 3.17.x of amCarts and the chartScrollBar attached to the category axis would respect the `maxSelectedTime` property of the chart. On upgrading to v 3.18.x, the scroll bar no longer does. The chart/graph will actually respect the `maxSelectedTime` value but the scroll bar gets out of sync. the scroll bar size/position won't match that of the graph as you scroll.

**Comment by martynasma** [comment]
Thank you for bringing this to our attention.

The bug is confirmed.

We'll let you know when the fix is available.

**Comment by martynasma** [comment]
Hey,

This was solved in 3.19.0. (just released)

Thanks!
