### ISSUE TITLE
redundant margin

### ISSUE THREAD

**Issue by DimaRGB** [amcharts/amcharts3#135]
Hello.
Why need this margin around chart ?

http://joxi.ru/LmGnwWGURD8P1r

**Comment by martynasma** [comment]
We found that having margins around chart is helpful. If you have any other elements adjacent to chart, or other charts, they need some "padding" or they look very crammed together.

To disable margins on sides that do not have any axis, simply set their margin setting, i.e. `marginLeft: 0`.

To reduce margin on sides that have axes, use [`autoMarginOffset`](http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#autoMarginOffset).
