### ISSUE TITLE
please publish latest versions to npm

### ISSUE THREAD

**Issue by DimaRGB** [amcharts/amcharts3#137]
now on [npm 3.21.2](https://www.npmjs.com/package/amcharts3)
but on [github 3.21.6](https://github.com/amcharts/amcharts3/releases)

many thanks for great library :)

**Comment by martynasma** [comment]
The package on npm is not official package. It was created by someone else, we don't have any control on. We're currently working on taking over that package so we can maintain it properly, but until it happens I suggest you use our GitHub repo for the latest version.

Sorry for the inconvenience.

**Comment by DimaRGB** [comment]
oh, sure, thanks.
