### ISSUE TITLE
the image path is 404 in vue-cli

### ISSUE THREAD

**Issue by qianzhiyue** [amcharts/amcharts3#139]
I used the amcharts in vue-cli, but the image path is 404,
![1](https://user-images.githubusercontent.com/33440545/32475293-fdbe4ea6-c3ab-11e7-808d-fc6a58e17be4.PNG)
![image](https://user-images.githubusercontent.com/33440545/32475348-44206c80-c3ac-11e7-8bf6-482bed8a2ab3.png)
so,How to show the image？

**Comment by martynasma** [comment]
You may need to explicitly specify the location of images on your server using `path` property:

http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#path
