### ISSUE TITLE
How to use drawing tools like Fibonacci Arc etc in AmStockChart

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#14]
I have seen websites like http://thestockmarketwatch.com/stock/stock-chart.aspx?stock=AAPL
use the drawing toolbox but I am unable to find these options in my library.  What am I missing.  I also do not see any form of documentation around it.  Please help

**Comment by martynasma** [comment]
Hi there,

The website you have referred to does not use amCharts libraries.

I'm afraid at this time we don't provide Fibonacci or other automatically-calculated indicators.

**Comment by debsush** [comment]
Noted.  But can Amcharts enable me to create two parallel line charts with a color filling the area between the two lines.  I would need to use this feature to enhance some of my technical charts

**Comment by gogglespisano** [comment]
Have you looked at the demos?  There are several examples of candlesticks, and you can fill between lines on a graph.  I've used that feature.

https://www.amcharts.com/demos/

**Comment by debsush** [comment]
Thank you team.  This is excellent stuff.  I will close the issue here
