### ISSUE TITLE
How to solve the abscissa overflow

### ISSUE THREAD

**Issue by kanJJ** [amcharts/amcharts3#143]
![capture2222](https://user-images.githubusercontent.com/26382575/32765804-24ce1d32-c947-11e7-9713-c72d4ad2e601.PNG)

like this picture, Date does not appear complete， so I don`t know how to solve it. Please help me ,
Thank you.

**Comment by martynasma** [comment]
Does this chart use `parseDates`? If it does it should not cut off dates like these since they are always positioned to the right of the grid.

If you could share your chart code and data, I'd probably be able to provide more insight.

**Comment by kanJJ** [comment]
I don`t use parseDates, and I also dont`t know how to use it. I just use "const casettings = new AmCharts.CategoryAxesSettings();" and set some attributes, like  'equalSpacing','groupToPeriods','dateFormats'. 
data format like this:"21/11/2012,0.1290,0.1290,0.1290,0.1290,,,,,,,,,,,,,,0.1288,0.1275"
this means "date,open,low,high,close,,,,,,,,,,,,,,support level,resistance level",
Can you teach me how to solve this problem?

**Comment by martynasma** [comment]
Sure.

Would you be able to provide your chart config and data so that I know what we're dealing with?

If you could create a working demo on CodePen that would be great.

**Comment by kanJJ** [comment]
sorry, because company`s security, I can not show you more information, only these below:
const chartData = AmCharts.parseCSV(csvChartDataSet, { 'useColumnNames': true });
		const sliderData = AmCharts.parseCSV(csvSliderDataSet, { 'useColumnNames': true });

		// Chart //////////////////////////////////////////
		const chart = new AmCharts.AmStockChart();

		if (StorageUtil.getLocale() === 'zh_CN' || StorageUtil.getLocale() === 'zh_HK')
			chart.language = 'zh';
		// Chart version
		chart.version = 'v1.0.0';
		// The path of amcharts
		chart.path = '../amcharts/';
		// The path of amcharts
		chart.dataDateFormat = 'DD/MM/YYYY JJ:NN';

		// AmBalloon //////////////////////////////////////////
		const amBalloon = new AmCharts.AmBalloon();
		amBalloon.showBullet = true;
		amBalloon.color = '#000000';
		amBalloon.textAlign = 'left';
		amBalloon.borderAlpha = 1;
		amBalloon.borderColor = '#FFFFFF';
		amBalloon.borderThickness = 2;
		amBalloon.cornerRadius = 0;
		amBalloon.shadowAlpha = 0.4;
		amBalloon.shadowColor = '#000000';
		amBalloon.fillAlpha = 0.8;
		amBalloon.textAlign = '#FFFFFF';

		// Data Sets ////////////////////////////////////////// Chart data set
		const chartDataSet = new AmCharts.DataSet();
		chartDataSet.title = "Exchange Rate Data Set";
		chartDataSet.categoryField = "date";
		// Fields mapping
		chartDataSet.fieldMappings = [
			{
				fromField: 'open',
				toField: 'open'
			}, {
				fromField: 'high',
				toField: 'high'
			}, {
				fromField: 'low',
				toField: 'low'
			}, {
				fromField: 'close',
				toField: 'close'
			}, {
				fromField: 'sma',
				toField: 'sma'
			}, {
				fromField: 'rsi',
				toField: 'rsi'
			}, {
				fromField: 'resistanceLevel',
				toField: 'resistanceLevel'
			}, {
				fromField: 'supportLevel',
				toField: 'supportLevel'
			}
		];
		chartDataSet.dataProvider = chartData;

		// Slider data set
		const sliderDataSet = new AmCharts.DataSet();
		sliderDataSet.title = "Slider Data Set";
		sliderDataSet.categoryField = "date";
		// Fields mapping
		sliderDataSet.fieldMappings = [
			{
				fromField: 'close',
				toField: 'value'
			}
		];
		sliderDataSet.dataProvider = sliderData;

		// Set data sets to the chart
		chart.dataSets = [chartDataSet, sliderDataSet];

		// PANELS /////////////////////////////////////////// Exchange rate stock panel
		const symbolTitle = symbol === '^USDX' || symbol === 'XAUCAD' ? chartLabels['^USDX'] : `${ccyCod[symbol.split('/')[0]]}/${ccyCod[symbol.split('/')[1]]}`;
		const exchangeRateStockPanel = new AmCharts.StockPanel();
		exchangeRateStockPanel.showCategoryAxis = true;
		exchangeRateStockPanel.title = symbolTitle;
		exchangeRateStockPanel.percentHeight = 100;
		exchangeRateStockPanel.dataDateFormat = 'DD/MM/YYYY JJ:NN';
		exchangeRateStockPanel.plotAreaBorderAlpha = 1;
		exchangeRateStockPanel.plotAreaBorderColor = '#AEAEAE';

		// Add value axes Close value
		const closeValueAxis = new AmCharts.ValueAxis();
		closeValueAxis.position = "right";
		//closeValueAxis.minimum = resistanceLevel;
		//closeValueAxis.maximum = supportLevel;
		const supGuides = new AmCharts.Guide();
		const resGuides = new AmCharts.Guide();
		supGuides.value = supportLevel;
		supGuides.lineAlpha = 0;
		resGuides.value = resistanceLevel;
		resGuides.lineAlpha = 0;
		closeValueAxis.guides = [supGuides, resGuides];
		closeValueAxis.minMaxMultiplier = 1.3;
		closeValueAxis.includeAllValues = true;
		closeValueAxis.includeGuidesInMinMax = true;

		exchangeRateStockPanel.addValueAxis(closeValueAxis);

		// Exchange rate graph of the exchange rate stock panel
		const exchangeRateGraph = new AmCharts.StockGraph();
		exchangeRateGraph.openField = "open";
		exchangeRateGraph.closeField = "close";
		exchangeRateGraph.highField = "high";
		exchangeRateGraph.lowField = "low";
		exchangeRateGraph.title = chartSettings.amstock_graph_close_title;
		exchangeRateGraph.valueField = "close";
		exchangeRateGraph.type = "line";
		exchangeRateGraph.lineThickness = 1.6;
		exchangeRateGraph.showBalloon = true;
		exchangeRateGraph.balloon = amBalloon;
		exchangeRateGraph.balloonText = chartSettings.amstock_settings;
		exchangeRateGraph.fillAlphas = 0.7;
		exchangeRateGraph.fillColors = '#ECF9F9';
		exchangeRateGraph.useDataSetColors = false;
		exchangeRateGraph.lineColor = "#BFEAEA";
		exchangeRateGraph.dateFormat = 'DD/MM/YYYY JJ:NN';
		exchangeRateGraph.valueAxis = closeValueAxis;
		exchangeRateGraph.visibleInLegend = false;

		exchangeRateStockPanel.addStockGraph(exchangeRateGraph);

		// SMA graph of the exchange rate stock panel
		const smaGraph = new AmCharts.StockGraph();
		smaGraph.title = `${chartLabels[sma.replace(/~/g, '') || 0]}:`;
		smaGraph.valueField = "sma";
		smaGraph.type = "line";
		smaGraph.lineThickness = 1.6;
		smaGraph.showBalloon = true;
		smaGraph.useDataSetColors = false;
		smaGraph.lineColor = "#BBED4F";
		smaGraph.dateFormat = 'DD/MM/YYYY JJ:NN';

		if (isShowSMAGraph) {
			exchangeRateStockPanel.addStockGraph(smaGraph);
		}

		// Trend line Resistance level
		const resistanceLevelTrendLine = new AmCharts.TrendLine();
		resistanceLevelTrendLine.balloonText = `${chartLabels.resistance_level_label} ${resistanceLevel}`;
		resistanceLevelTrendLine.initialDate = chartData[0].date;
		resistanceLevelTrendLine.initialValue = resistanceLevel;
		resistanceLevelTrendLine.finalDate = chartData[chartData.length - 1].date;
		resistanceLevelTrendLine.finalValue = resistanceLevel;
		resistanceLevelTrendLine.dashLength = 8;
		resistanceLevelTrendLine.lineThickness = 1;
		resistanceLevelTrendLine.lineAlpha = 1;
		resistanceLevelTrendLine.lineColor = '#14B0B0';

		// Support level
		const supportLevelTrendLine = new AmCharts.TrendLine();
		supportLevelTrendLine.balloonText = `${chartLabels.support_level_label} ${supportLevel}`;
		supportLevelTrendLine.initialDate = chartData[0].date;
		supportLevelTrendLine.initialValue = supportLevel;
		supportLevelTrendLine.finalDate = chartData[chartData.length - 1].date;
		supportLevelTrendLine.finalValue = supportLevel;
		supportLevelTrendLine.dashLength = 8;
		supportLevelTrendLine.lineThickness = 1;
		supportLevelTrendLine.lineAlpha = 1;
		supportLevelTrendLine.lineColor = '#14B0B0';

		if (isShowTrendLine) {
			exchangeRateStockPanel.addTrendLine(resistanceLevelTrendLine);
			exchangeRateStockPanel.addTrendLine(supportLevelTrendLine);
		}

		// create stock legend
		const stockLegend = new AmCharts.StockLegend();
		stockLegend.markerType = 'circle';
		stockLegend.markerSize = 10;
		exchangeRateStockPanel.stockLegend = stockLegend;

		// Set exhcange rate stock panel to the chart
		chart.panels = [exchangeRateStockPanel];

		// ChartScrollbarSettings ////////////////////////////////////
		const sbsettings = new AmCharts.ChartScrollbarSettings();
		sbsettings.graph = exchangeRateGraph;
		sbsettings.graphType = 'line';
		sbsettings.height = 25;
		sbsettings.gridAlpha = 1;
		sbsettings.gridColor = '#FFFFFF';
		sbsettings.backgroundAlpha = 1;
		sbsettings.backgroundColor = '#EEEEEE';
		sbsettings.graphFillAlpha = 1;
		sbsettings.graphFillColor = '#A7E4F3';
		sbsettings.graphLineAlpha = 1;
		sbsettings.graphLineColor = '#66DAF7';
		sbsettings.dragIcon = 'dragIconRoundSmall';
		sbsettings.dragIconHeight = 25;
		sbsettings.dragIconWidth = 25;
		sbsettings.dragIcon = 'dragIconRoundSmall';
		sbsettings.selectedBackgroundAlpha = 1;
		sbsettings.selectedBackgroundColor = '#00CCFF';
		sbsettings.selectedGraphFillAlpha = 1;
		sbsettings.selectedGraphFillColor = '#33ADCC';
		sbsettings.selectedGraphLineAlpha = 1;
		sbsettings.selectedGraphLineColor = '#7D8081';
		sbsettings.hideResizeGrips = true;
		sbsettings.usePeriod = `DD`;
		chart.chartScrollbarSettings = sbsettings;

		// ChartCursorSettings ////////////////////////////////////
		const ccsettings = new AmCharts.ChartCursorSettings();
		ccsettings.valueBalloonsEnabled = true,
			ccsettings.valueLineBalloonEnabled = true,
			ccsettings.valueLineEnabled = true,
			ccsettings.bulletsEnabled = true,
			ccsettings.cursorColor = '#00BDD6';
		ccsettings.categoryBalloonColor = '#00BDD6',
			ccsettings.color = '#FFFFFF',
			ccsettings.categoryBalloonDateFormats = [
				{
					period: 'fff',
					format: 'JJ:NN:SS'
				}, {
					period: 'ss',
					format: 'JJ:NN:SS'
				}, {
					period: 'mm',
					format: 'JJ:NN'
				}, {
					period: 'hh',
					format: 'JJ:NN'
				}, {
					period: 'DD',
					format: 'MMM DD'
				}, {
					period: 'WW',
					format: 'MMM DD'
				}, {
					period: 'MM',
					format: 'MMM'
				}, {
					period: 'YYYY',
					format: 'YYYY'
				}
			]
		chart.chartCursorSettings = ccsettings;

		// CategoryAxesSettings ////////////////////////////////////
		const casettings = new AmCharts.CategoryAxesSettings();
		casettings.equalSpacing = true;
		casettings.groupToPeriods = [
			"5mm",
			"15mm",
			"hh",
			"DD",
			"WW",
			"MM",
			"YYYY"
		]
		casettings.dateFormats = [
			{
				period: 'fff',
				format: 'JJ:NN:SS'
			}, {
				period: 'ss',
				format: 'JJ:NN:SS'
			}, {
				period: 'mm',
				format: 'JJ:NN'
			}, {
				period: 'hh',
				format: 'JJ:NN'
			}, {
				period: 'DD',
				format: 'DD/MM'
			}, {
				period: 'WW',
				format: 'DD/MM'
			}, {
				period: 'MM',
				format: 'MM/YYYY'
			}, {
				period: 'YYYY',
				format: 'MM/YYYY'
			}
		],
			casettings.minPeriod = `${intervalUnit}${intervalUnit}`,
			casettings.maxSeries = 0;
		chart.categoryAxesSettings = casettings;
		

		// Disable typing feild date
		chart.addListener('rendered', function (e) {
			const fields = e
				.chart
				.div
				.getElementsByClassName("amChartsInputField");
			for (let i = 0; i < fields.length; i++) {
				fields[i].readOnly = true;
			}
		});

		// Write this chart to DOM
		chart.write(id);


DATA:{"csvChartDataSet":"22/11/2013,0.9233,0.9139,0.9249,0.9166,,,,,,,,,,,,,,0.9113,0.6433\n25/11/2013,0.9164,0.9117,0.9188,0.9158,,,,,,,,,,,,,,0.9113,0.6433\n26/11/2013,0.9160,0.9086,0.9204,0.9127,,,,,,,,,,,,,,0.9113,0.6433\n27/11/2013,0.9126,0.9061,0.9137,0.9077,,,,,,,,,,,,,,0.9113,0.6433\n28/11/2013,0.9077,0.9072,0.9149,0.9096,,,,,,,,,,,,,,0.9113,0.6433\n29/11/2013,0.9098,0.9052,0.9140,0.9110,,,,,,,,,,,,,,0.9113,0.6433\n02/12/2013,0.9107,0.9086,0.9168,0.9100,,,,,,,,,,,,,,0.9113,0.6433\n03/12/2013,0.9104,0.9055,0.9146,0.9136,,,,,,,,,,,,,,0.9113,0.6433\n04/12/2013,0.9135,0.8995,0.9141,0.9025,,,,,,,,,,,,,,0.9113,0.6433\n05/12/2013,0.9029,0.9000,0.9077,0.9062,,,,,,,,,,,,,,0.9113,0.6433\n06/12/2013,0.9061,0.8988,0.9117,0.9100,,,,,,,,,,,,,,0.9113,0.6433\n09/12/2013,0.9124,0.9068,0.9135,0.9112,,,,,,,,,,,,,,0.9113,0.6433\n10/12/2013,0.9110,0.9076,0.9167,0.9150,,,,,,,,,,,,,,0.9113,0.6433\n11/12/2013,0.9150,0.9043,0.9152,0.9048,,,,,,,,,,,,,,0.9113,0.6433\n12/12/2013,0.9047,0.8912,0.9077,0.8933,,,,,,,,,,,,,,0.9113,0.6433\n13/12/2013,0.8936,0.8906,0.8969,0.8962,,,,,,,,,,,,,,0.9113,0.6433\n16/12/2013,0.8959,0.8924,0.8969,0.8947,,,,,,,,,,,,,,0.9113,0.6433\n17/12/2013,0.8947,0.8879,0.8957,0.8892,,,,,,,,,,,,,,0.9113,0.6433\n18/12/2013,0.8896,0.8828,0.8943,0.8860,,,,,,,,,,,,,,0.9113,0.6433\n19/12/2013,0.8860,0.8820,0.8874,0.8866,,,,,,,,,,,,,,0.9113,0.6433\n20/12/2013,0.8866,0.8852,0.8934,0.8921,,,,,,,,,,,,,,0.9113,0.6433\n23/12/2013,0.8920,0.8913,0.8958,0.8934,,,,,,,,,,,,,,0.9113,0.6433\n","dataTimeZone":"Asia/Hong_Kong","endDate":"20171121","endTime":"0800","flag":"1500366617543","interval":"1","intervalUnit":"D","lastUpdatedTime":"201711210800","period":"4","periodHigh":"0.9504","periodLow":"0.6824","periodUnit":"Y","reasonCode":"000","resistanceLevel":"0.9113","responseCode":"0","spotReference":"0.7578","startDate":"20131122","startTime":"0800","supportLevel":"0.6433","symbol":"AUD/USD","todayHigh":"0.7595","todayLow":"0.7570","userTimeZone":"Asia/Hong_Kong"
}
This is an exchange rate data, it means rates of  AUD to USD , period is 4Y. interval is 1D. if you have some idea, please tell me , thank you very much.

**Comment by martynasma** [comment]
OK, so I finally was able to make it work. Sorry for the delay.

https://codepen.io/team/amcharts/pen/33d9746756551e8a5acfe94ef594ea16?editors=0010

It looks like you are using `equalSpacing = true`, which forces category axis into category mode, and therefore centers category labels.

If category is close enough to the edge of the chart, it's clipped.

So there are a couple options for you:

1) Disable `equalSpacing = true`;

2) Add some margin around panels:

```
chart.panelsSettings.marginLeft = 10;
chart.panelsSettings.marginRight = 10;
```

I hope this helps.

**Comment by kanJJ** [comment]
I used the second method， it`s working!!! thank you for your advice.

**Comment by martynasma** [comment]
Great! Glad I could help.
