### ISSUE TITLE
Random line appears on charts ocassionally

### ISSUE THREAD

**Issue by 3zzy** [amcharts/amcharts3#146]
![Image of bug](https://i.imgur.com/fxNyy3K.png)

We have these diagonal lines appearing over the chart occasionally. Is this a known bug? Any workaround?

**Comment by martynasma** [comment]
This is due to a bug in Chrome 62.

Try upgrading to the latest version of amCharts, which implements a workaround for this bug.

Make sure you clear you browser cache.

Let me know if you are still having the issue after upgrading.

**Comment by kotcev** [comment]
Can you link the commit with the workaround?

**Comment by martynasma** [comment]
Sure:
https://github.com/amcharts/amcharts3/commit/2fa0269779665bea270ddda447b4cc59418e999b

**Comment by jbclew** [comment]
we are seeing the same thing with amcharts v. 3.21.12  and chrome 63.0.3239.132 (64-bit).  The line seems to go away if we run additional javascript on the page, but returns if the page is refreshed.

![amchart](https://user-images.githubusercontent.com/18448844/35071331-3aad4a6c-fb95-11e7-977c-799445a5015c.png)

**Comment by martynasma** [comment]
@jbclew Can you share a code for your chart or a link with the actual chart?

**Comment by jbclew** [comment]
please go to https://skalastaging.metergroup.com/accounts/login/

login: amcharts@limiteduser.com
pw: amcharts2017

then go to the url:
https://skalastaging.metergroup.com/location_detail_fullscreen/55

**Comment by martynasma** [comment]
Thanks for the link.

For the past few days, I'm trying to view your chart, thinking maybe it updates differently during different parts of the day. But all I get is this:

<img width="1907" alt="chrome_2018-01-26_22-14-17" src="https://user-images.githubusercontent.com/1458520/35458793-6ae1d4ca-02e6-11e8-98b1-15b630a50bde.png">

Am I missing something?

**Comment by jbclew** [comment]
hmm,  We try it here and have 2 developers where it shows up like yours and
3 where it shows up like the way I posted.  All using the same version of
chrome, accessing the same graph and clearing any cache on the browser.
Any ideas on why that would happen?

On Fri, Jan 26, 2018 at 12:15 PM, Martynas Majeris <notifications@github.com

**Comment by jbclew** [comment]
Nevermind, we just all updated today to the lastest version of Chrome (
64.0.3282.119 ) and it seems to work correctly now.

**Comment by martynasma** [comment]
Alright. Let's chalk it up to a fixed bug in Chrome.

Feel free to reopen this or (even better) contact@amcharts.com if the bug resurfaces.
