### ISSUE TITLE
Gantt Chart Zoomed Issue

### ISSUE THREAD

**Issue by ushulau** [amcharts/amcharts3#15]
gantt chart does not dispatch "zoomed" event on zooming only single time during creation

**Comment by martynasma** [comment]
"zoomed" event is dispatched on category axis zoom only. On GANTT chart it's the vertical axis.

If you are referring to the horizontal zooming, that's value axis. It has its own zoom event "axisZoomed" which needs to be applied directly to that value axis:

```
  "valueAxis": {
    "type": "date",
    "minimum": 7,
    "maximum": 31,
    "listeners": [{
      "event": "axisZoomed",
      "method": function(event) {
        console.log(event);
      }
    }]
```

Here's a working demo:
http://codepen.io/team/amcharts/pen/df8520f8020c255d908faeaf4bc44c85

And here's the relative description of the event in docs:
http://docs.amcharts.com/3/javascriptcharts/ValueAxis#axisZoomed

I hope this helps.
