### ISSUE TITLE
Ability to set the Container Id for ChartScrollbar

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/amcharts3#161]
Hi there, 

Is there a way to set the container of the ChartScrollbar just like the legend component.

Best Regards,
Mark

**Comment by martynasma** [comment]
No, I'm afraid.

**Comment by kevzlou7979** [comment]
How about ability to hide the Chart Area not the scrollbar, is that possible.

Thanks,
Mark

**Comment by martynasma** [comment]
Yes. The scrollbar is constant width, so if you reduce chart height to scrollbar's height, you'll end up with just the scrollbar.

**Comment by kevzlou7979** [comment]
Thanks @martynasma , tried your suggestion and everything works. Closing now this issue. Hope If someone is having the same issue this could be the workaround.
