### ISSUE TITLE
Question - Is it allowed to used this on an Open Source Project?

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/amcharts3#163]
Hi there,

I'am a lead contributor on Gwt Material Project (Open Source) - is it allowed to embed AmCharts free version on our demo showcase as long as the copyright or amchart label is still there?

Best Regards,
Mark

**Comment by martynasma** [comment]
Hi Mark,

Absolutely. The only requirement for the free version is the branding link. As long as that is there, you can do whatever you want with the free version.

Thanks for checking!

Martynas

**Comment by kevzlou7979** [comment]
Ok thanks for the information, we appreciate it. Loving your AmChart Library

**Comment by martynasma** [comment]
Thanks!
