### ISSUE TITLE
Cannot read property 'getBBox' of undefined

### ISSUE THREAD

**Issue by mharini** [amcharts/amcharts3#168]
On mouse drag and on hover event over my rendered amchart, I am getting the following error.

`Runtime Error`
`Cannot read property 'getBBox' of undefined`
`Stack`
`TypeError: Cannot read property 'getBBox' of undefined`
`    at Object.handleGuideOver (http://localhost:8100/assets/js/amcharts.js:42:18)`
`    at SVGTextElement.<anonymous> (http://localhost:8100/assets/js/amcharts.js:42:514)`
`    at SVGTextElement.o [as __zone_symbol___onmouseover]` `(http://localhost:8100/build/polyfills.js:2:24340)`
 `   at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)`
 `   at Object.onInvokeTask (http://localhost:8100/build/vendor.af6d443c816c049b52be.js:4500:37)`
`    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)`
 `   at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)`
 `   at SVGTextElement.invoke (http://localhost:8100/build/polyfills.js:3:10945)`

I am using **"3.21.1"** amcharts version.
The type of chart I am trying to render is **"serial.js"**

Can someone help me solve this issue?

**Comment by martynasma** [comment]
Unfortunately, it's not possible to determine the cause of this issue just from error message.

Do you have this online somewhere where we can test?

Also, does the problem persist with the most recent version? (3.21.12)

**Comment by mharini** [comment]
Yes. The problem occurs in the latest version too.

**Comment by mharini** [comment]
Here is the JSFiddle link to reproduce this issue. 

[https://jsfiddle.net/xfvdcq24/](url)

Hover over the guide label "**14**" placed over top of the first bar. You can see the above mentioned error in console.

**Comment by mharini** [comment]
@martynasma Found any fix regarding this issue?

**Comment by martynasma** [comment]
Hi there,

We have just released a new version (3.21.13) which should fix the issue.

Please don't hesitate to get back to us if the problem persists after upgrading.
