### ISSUE TITLE
Save, Publish and Embed Charts

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#17]
Hi,

Is it currently possible to save, publish and create embed Wordpress URL links just like in the live editor in our own personal charts that we may want to build within our apps.  

I am referring to the article below which seems only availble if I use the live editor

https://www.amcharts.com/tutorials/embedding-live-editor-charts-into-wordpress/ 

I am using amCharts through a package in R called rAmcharts

Thank you
SD

**Comment by martynasma** [comment]
Hi there,

I'm afraid I'm not familiar with neither R or the package you mentioned. However, Live Editor supports oEmbed specification. If R supports adding oEmbed items, you can embed Live Editor charts in it.

Search for "amcharts" here:

http://oembed.com/#section7

You will get all the URLs required for oembeding charts.

I hope this helps.

**Comment by debsush** [comment]
Hi, 

I am a beginner but I am building the charts in my app using your charting library.  This will allow users to view the charts within my app.  How can a user in my app extract the URL of the chart which he/she can later embed in his/her wordPress blogs or share the chart within my app in social media.

Please note that the user is customizing the amChart created within my app and not using the Live Editor

Thank you,
SD

**Comment by martynasma** [comment]
I'm not entirely sure. That's part of your application design.

I suppose you could create your charts on a separate page, then let your users embed using an iframe. Or, you could implement oembed support in your application as well. WP supports oembed out of the box, so they should be able to include your charts.

I suggest reviewing the documentation posted on http://oembed.com/ and assess whether it is something that could work for the purposes of your users.

**Comment by debsush** [comment]
Thank you for the direction.  Appreciate it.
