### ISSUE TITLE
Graphs toggled by default

### ISSUE THREAD

**Issue by SaraGar** [amcharts/amcharts3#183]
Hi! 
I would like to have all but one of the graphs toggled (not showing up) when the chart is drawn, is it possible?

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **37160**.
> (replying here will automatically notify amCharts support agent)

Hi there,

You can set your graph objects' [hidden](http://docs.amcharts.com/3/javascriptcharts/AmGraph#hidden) property to true in your makeChart call to hide them on init:

```
AmCharts.makeChart("chartdiv", {
  // ...
  "graphs": [{
     // ...
     "hidden": true,
     // ...
  }, 
  // repeat for each graph you want to hide by default
  ],
  // ...
});
```

Note that we have a demo that also shows the hidden property in action on our demos page here: https://www.amcharts.com/demos/stacked-area/ 

I hope this helps.

Best,

Anthony Piris
amCharts

**Comment by SaraGar** [comment]
Thank you!!

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **37160**.
> (replying here will automatically notify amCharts support agent)

You're welcome!

Please feel free to reach out to us again if you have any other questions.

Best,

Anthony Piris
amCharts
