### ISSUE TITLE
Gauge arrow pointing wrong value and spinning multiple times

### ISSUE THREAD

**Issue by brunoalreis** [amcharts/amcharts3#184]
When i have a gauge and the value is bigger than the axes value, the arrow starts spining multiple times and stop in a random value (at least is random for me).

You can reproduce this in this demo https://www.amcharts.com/demos/angular-gauge/, if you open in jsfiddle and in this line you change the value from 200 to 2000:

var value = Math.round( Math.random() * 200 );

The problem is that, for example, the user see the value 600 and the arrow is pointing close to 20.

See this example in our implementation:
![image](https://user-images.githubusercontent.com/548412/41096677-3e8d086c-6a4d-11e8-9040-056647fa959e.png)

**Comment by brunoalreis** [comment]
Hi Anthony Piris,

Yes it helped. Thank you.

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **37353**.
> (replying here will automatically notify amCharts support agent)

You're welcome.

Please feel free to contact us again if you have any other questions.

Best,

Anthony Piris
amCharts
