### ISSUE TITLE
A serial graph not clipping when scrolling.

### ISSUE THREAD

**Issue by erfg** [amcharts/amcharts3#19]
I was unable to reproduce the error in the live editor, but it looks like in the image. In the date/time series, the graph isn't clipping to the graph frame. In other examples of serial graphs works fine but in those is buggy... I've copied/pasted the code from the example.

Version: 3.18.6
Browsers: Chrome/Firefox
OS: Linux/OSX

![amcharts](https://cloud.githubusercontent.com/assets/4007668/13608783/972101dc-e556-11e5-9083-5358edf7c4e0.png)

**Comment by martynasma** [comment]
Do you by any chance use the chart on an AngularJS or some other framework that uses `base href`?

If that is so, try adding the following line **before** any other chart code:

```
AmCharts.baseHref = true;
```

**Comment by erfg** [comment]
That was the problem. Thank you!
