### ISSUE TITLE
How to dislay Y-Axis Outside of graph

### ISSUE THREAD

**Issue by Nagavijay-kolla** [amcharts/amcharts3#196]
Hi Team

In Am Chart, Y-Axis is overriding data as shown in below image.

![amchart_issue](https://user-images.githubusercontent.com/36224971/43364121-bde8f046-9331-11e8-8315-a93a62526d50.png)

I have tried ** inside: false**  if I config inside false the y-axis disappearing completely. 
Please help me in this.

Thank in Advance.

**Comment by Nagavijay-kolla** [comment]
Yeah, It's working fine thank you so much

**Comment by martynasma** [comment]
You're welcome!
