### ISSUE TITLE
amcharts with Webpack

### ISSUE THREAD

**Issue by orangecoding** [amcharts/amcharts3#20]
Hey,

is there a plan when AmCharts will work nicely together with Es6 and Webpack? It's currently a pain to get AmCharts running within finding all needed plugins and images using webpack. Is there a roadmap anywhere?

**Comment by mkozhukharenko** [comment]
I using es6 modules to import a library
```
import AmCharts from 'exports?window.AmCharts!amcharts3';
import 'exports?window.AmSerialChart!amcharts3/amcharts/serial';
```

+1 for such kind of roadmap!

**Comment by mkozhukharenko** [comment]
+1
need to add UMD/AMD support.

**Comment by martynasma** [comment]
Hi there,

I'm afraid we currently do not have Webpack support or related documentation.

**Comment by ahmedelgabri** [comment]
@orangecoding here is what I'm doing.

### Install amcharts3
```sh
$ npm i -S amcharts/amcharts3#838909c # The hash of the latest release 
```

### Created an entry file for amcharts to use in Webpack alias `amcharts.js`
```js
require('amcharts3/amcharts/amcharts');
require('amcharts3/amcharts/serial');
// require more stuff that you need from amcharts
```

### Webpack
```js
 resolve: {
    alias: {
      amcharts: path.resolve('./path/to/amcharts.js')
  }
```

### in your main JavaScript file

```js
require('amcharts');

or 

import 'amcharts';
```

It's **ugly** and **hacky** but unfortunately the only solution I managed to make it work. I'd prefer a proper CommonJS/ES2015 support though.

**Comment by mkozhukharenko** [comment]
Just use simple import/require without webpack alias:
```
require('amcharts3/amcharts/amcharts');
```
Check [this](https://github.com/mkozhukharenko/ums-frontend/blob/master/src/modules/statistics/containers/Chart.js#L2-L7) example

**Comment by ahmedelgabri** [comment]
@mkozhukharenko this also works, but in my case I wanted to require a couple of things _always_ that's why I created the entry file & the alias.

**Comment by mkozhukharenko** [comment]
@ahmedelgabri you are right, in this case your option is better.

**Comment by anirudhsamudrala** [comment]
@mkozhukharenko @ahmedelgabri I am currently on Angular 2 with webpack, I am having trouble installing and getting it wotk. Can you please let me know the steps to get it work?

**Comment by anirudhsamudrala** [comment]
@martynasma do we have support for webpack yet? I am running on Angular2 and webpack, I dont find any documentation.

**Comment by Pauan** [comment]
@anirudhsamudrala AmCharts does not have support for Webpack, but [`@amcharts/amcharts3-angular`](https://github.com/amcharts/amcharts3-angular2#installation) does have support for Webpack.

I recommend using the [`angular-cli`](https://github.com/angular/angular-cli#installation) tool. It simplifies configuration and building the project.

After you have set up [`angular-cli`](https://github.com/angular/angular-cli#installation), you can then follow [the directions on the `@amcharts/amcharts3-angular` repository](https://github.com/amcharts/amcharts3-angular2#installation).

**Comment by ssc-hrep3** [comment]
Would be great to have the default version of `amCharts` to support webpack. I would need it for my build process with Vue.js ([vue-webpack](https://github.com/vuejs-templates/webpack)). At the moment, I'm using the workaround over the `window` object.

**Comment by benmccann** [comment]
For amstock, I did the following.

In `package.json`:

    "dependencies": {
      "amstock3": "github:amcharts/amstock3"
    }

In my JavaScript:

    require('amstock3/amcharts/amcharts');
    require('amstock3/amcharts/serial');
    require('amstock3/amcharts/amstock');

**Comment by driskull** [comment]
We would also like to see this supported.

**Comment by sylido** [comment]
Please ?

**Comment by marlondom** [comment]
```Module not found: Error: Can't resolve 'amstock3/amcharts/images' in```

**Comment by martynasma** [comment]
Just to put this into perspective: while we do have plugins/wrappers for particular frameworks like Angular2+ and React, amCharts itself was not build in a modular way and will not be modified to act as such.

If this is a requirement for you, we strongly suggest checking out amCharts 4 - our next charting library, which is currently in public preview, and supports ES6 / TS modules, and all kinds of current frameworks:

https://www.amcharts.com/docs/v4/getting-started/integrations/
