### ISSUE TITLE
How to show only one item Pie Chart & Clear (without information beside chart) & Dynamic allLabels's text

### ISSUE THREAD

**Issue by icangku** [amcharts/amcharts3#200]
![utilization-donut-chart](https://user-images.githubusercontent.com/14269158/44626120-770b5580-a941-11e8-8fd8-493d62de54f8.png)
I want to achieve like that

**Comment by icangku** [comment]
Yes I have, we need 2 items, ex : we want only to show 60% then the second item should be 100% - 60%, but I have new problems, 
1. I want pie clear as the picture because using amcharts there are information show in the chart, 
2. I cannot change allLabels in amcharts dynamically - to show like 60 Hertz

**Comment by martynasma** [comment]
To disable labels, simply set [`labelsEnabled`](http://docs.amcharts.com/3/javascriptcharts/AmPieChart#labelsEnabled) to `false`.

You can change `allLabels`, just remember to call `validateNow()` on a chart object afterwards.

```
chart.allLabels[0].text = "80";
chart.validateNow();
```

**Comment by icangku** [comment]
I mean after fetching data then show to chart

`var red = response.data.percent.red
pie.allLabels[0].text = red`

but its not working

**Comment by martynasma** [comment]
Are you also calling `chart.validateNow()`?

**Comment by icangku** [comment]
Thanks my bro, you saved me!
