### ISSUE TITLE
amCharts Script

### ISSUE THREAD

**Issue by ShamanLKG** [amcharts/amcharts3#201]
Hello,

I've tried many different configuration and the chart is still not loading when I put the script in a separate .js.

As an example I put the content between the <scritpt> </script> in amchart.js, load the script as follows in my html.

<script type="text/javascript" src="./src/js/amchart.js"></script>

But the chart is not loading. I also tried replacing "chartdiv" in the original code by document.getElementById("chartdiv"). No effect, the chart is blank.

What am I doing wrong?`

Thank you very much in advance for your help!

**Comment by ShamanLKG** [comment]
Actually solved, the chart must be loaded with <div id="chartdiv"> and not using the tag <canevas>

**Comment by Pauan** [comment]
I'm glad you were able to figure it out.

I'm going to close this issue, but please contact us again if you run into any more issues.
