### ISSUE TITLE
Line Series zooming on no data

### ISSUE THREAD

**Issue by christopherjbaker** [amcharts/amcharts3#206]
If you have a line series and you zoom into an area that has no data points, you get this error:

![image](https://user-images.githubusercontent.com/980338/46176026-d02d1880-c262-11e8-9bec-29d498dbb9a2.png)

As caused by this section of code. It is assuming there are data points.

![image](https://user-images.githubusercontent.com/980338/46176017-c4d9ed00-c262-11e8-8797-d9e6dde459a9.png)

**Comment by xorspark** [comment]
I think you meant to open this in the [amcharts4 repo](https://github.com/amcharts/amcharts4/). This repo is for v3, which doesn't have a LineSeries object. If you can provide a codepen that demonstrates this, that would help too.
