### ISSUE TITLE
Is it possible to add a context Menu when right clicking a StockGraph

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#21]
Hi,

Was wondering if it is possible to create a contextMenu when you right-click a stockGraph in a AmStockChart.  I am trying to give the user a chance to change the stockGrpah color or remove the stockGrpah through this contextMenu.  Appreciate if you could provide an example of such an implementation.

Thank you as always
SD

**Comment by martynasma** [comment]
No, I'm afraid there's no built-in capability for the context menu. Sorry.
