### ISSUE TITLE
Exported PNG has not same color with chart which i see

### ISSUE THREAD

**Issue by spider58** [amcharts/amcharts3#214]
Hello.

This image shows  my actual chart which i see on chrome

https://i.hizliresim.com/1E1aqG.png

I set chart options with below code. And i changing chart's container div's color with bgcolor probrammatically.

```
  "backgroundColor": bgcolor,
  "backgroundAlpha": 1,
  "legend": {
                useGraphSettings: true,
                "backgroundColor": bgcolor,
                "backgroundAlpha": 1,
              },
```
and this image shows what i see when i export my chart

https://i.hizliresim.com/X6V8mO.png

What is white areas. How can i change color of them with bgcolor. What property for this?

Thanks inadvance

**Comment by spider58** [comment]
https://www.amcharts.com/demos/exporting-chart-to-image/?theme=black

this sample has similiar problem. export is not considering chart theme. i need solution.

**Comment by xorspark** [comment]
You have to set the [`backgroundColor` in the export plugin](https://github.com/amcharts/export#user-content-complete-list-of-available-export-settings) as well.

```
export: {
  enabled: true,
  backgroundColor: bgcolor,
  // ...
}
```

**Comment by spider58** [comment]
> You have to set the [`backgroundColor` in the export plugin](https://github.com/amcharts/export#user-content-complete-list-of-available-export-settings) as well.
> 
> ```
> export: {
>   enabled: true,
>   backgroundColor: bgcolor,
>   // ...
> }
> ```

Thanks.
