### ISSUE TITLE
validateData() not working

### ISSUE THREAD

**Issue by yxxa** [amcharts/amcharts3#216]
hallo, can anyone help me

here is my flow:
1. the default value of "total guru", "total buku", "total karya ilmiah" is 0 (zero) saved in vuejs property
2. if selectbox was changed data/property will be updated like in the db

my problem is amcharts3 can't updated dinamically, i just read the documentation here http://docs.amcharts.com/3/javascriptmaps?search=validate and i found method validateData(). i trying to use this method but nothing happen :(

*u can see in the image i have, i just console.log the new value of "total guru" but chart is still 0 (zero)

![image 75](https://user-images.githubusercontent.com/25668079/48896874-46bd4f80-ee7b-11e8-9abc-05c5aa447ff9.png)

**Comment by RobbiesCode** [comment]
Hi,

While I am not much of a Vue-expert, I have managed to produce this little " component" that displays a chart and updates its data after clicking on a button. Here's the code:

**Template**

```
<template>
  <div id="app">
    <div id="chartdiv" style="width: 100%; height: 400px;"></div>
    <button v-on:click="changeData">Change Data</button>
  </div>
</template>
``` 

**Script**

```
<script>
export default {
  name: 'app',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  },
  created () {
    this.chart = AmCharts.makeChart("chartdiv",
      {
        "type": "serial",
        "categoryField": "type",
        "chartCursor": {},
        "graphs": [
          {
            "type": "column",
            "title": "Pizza types",
            "valueField": "sold",
            "fillAlphas": 0.8
          }
        ],

        "dataProvider": [
          { "type": "Margherita", "sold": 120 },
          { "type": "Funghi", "sold": 82 },
          { "type": "Capricciosa", "sold": 78 },
          { "type": "Quattro Stagioni", "sold": 71 }
        ]
      }
    );
  },
  methods: {
    changeData: function(event){

      this.chart.dataProvider = [
        { "type": "Margherita", "sold": 180 },
        { "type": "Funghi", "sold": 182 },
        { "type": "Capricciosa", "sold": 220 },
        { "type": "Quattro Stagioni", "sold": 250 }
      ];

      this.chart.validateData();

    }
  }
}
</script>
```

When the button is clicked, the method `changeData` is called. This methods sets a new `dataProvider` and refreshes the chart by calling `chart.validateData()`.

I have followed the steps from this tutorial (https://www.amcharts.com/kbase/using-amcharts-vue-js-webpack/) to set up this demo.

Hope this helps!

**Comment by yxxa** [comment]
wow, thanks for the help n thx for your time
actually I've solved my problem using this [way](https://stackoverflow.com/questions/44017891/pass-variable-to-amcharts-loadfile-method)

not much different in logic, but I am very grateful for your answer
*fyi im first using amcharts, rather difficult to read the documentation xD
