### ISSUE TITLE
Legend within the StockPanel

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#22]
Hi,

My AmStockChart has multiple panels and I would like to save on precious real estate by placing the legends within the stockpanel and removing any gaps between 2 stock panels.  Was wondering if it is possible.

Thank you
SD

**Comment by martynasma** [comment]
Hi,

No, I'm afraid there's no way to put the legend inside the plot area.

There is a workaround, though. You can put the legend in an external container, then position it over the plot area.

Here's an example:

http://codepen.io/team/amcharts/pen/e4637dc98be4369f0ae2db6deec689f0

**Comment by debsush** [comment]
Hi,

This is somewhat close but not quite there.  Can we improvise on this example as follows:
I would like this legend divID to be within a given panel.  But since I am adding new panels based on user input, the position of the panels is not fixed and hence I would need a trick to ensure my legend divID is within the given corresponding panel at the top.  Is it doable?

Thank you,
SD

**Comment by martynasma** [comment]
Technically it should be possible.

All panels are <divs> with class "amcharts-stock-panel-div" stored within parent <div> with class "amcharts-panels-div".

You could measure their position within their parent container and reposition their respective legends respectively.

I don't have a demo for that, but this is something that you might want to look into.

**Comment by debsush** [comment]
Thank you for your prompt response as always.  
I am new to Java and am using your Amcharts through R but I am assuming this piece of code should go into the Listener of each and every individual StockPanel every time it is rendered.

Was wondering if you could help me create a new demo or provide me the part of the code that should be tagged to the StockPanel.Listener which will enable me to detect the position of the panel and pass it into a div whose position can be controlled based on the position of the panel.  I would really appreciate your support. 

Thank you
SD

**Comment by martynasma** [comment]
I'm terribly sorry, but we don't have such an example ready-made.

And I don't know a thing about R :)
