### ISSUE TITLE
Unable to load Stock Graph in Safari

### ISSUE THREAD

**Issue by qalbit** [amcharts/amcharts3#221]
I am facing issues to load graph in **Safari** Browser. Working fine with _rest browser_.

I have integrated code
[Code Sample link](http://ruche.pluginweb.ch/graphs/poid-chart.php?id=12&time=5)

**Below code I have used to show data with AmStock Chart.**

`for (var i = 0,
     j = dataObj.length; i < j; i++) {
   var newDate = new Date(dataObj[i].date);
   RESULT.push({
      date : newDate,
      value : dataObj[i].value
   });
}

var CHART = new AmCharts.AmStockChart();
CHART.language = "fr";
CHART.dataDateFormat = "YYYY-MM-DD HH:NN:SS"

// Define Category Axis, Also minPeriod to "ss" for Seconds
var categoryAxisSetting = new AmCharts.CategoryAxesSettings();
categoryAxisSetting.minPeriod = "ss";
CHART.categoryAxesSettings = categoryAxisSetting;

// Add DATASETs
var dataSet = new AmCharts.DataSet();
dataSet.title = "Poids";
dataSet.color = "#01DCE3";
dataSet.fieldMappings = [{
   fromField : "value",
   toField : "value"
}];
dataSet.dataProvider = RESULT;
dataSet.categoryField = "date";

CHART.dataSets = [dataSet];

// Define Panel
var stockPanel = new AmCharts.StockPanel();
stockPanel.showCategoryAxis = true;
stockPanel.title = "Valeur";
stockPanel.eraseAll = false;

// Define Graph
var graph1 = new AmCharts.StockGraph();
graph1.id = "g1";
graph1.lineThickness = 2;
graph1.valueField = "value";

graph1.bullet = "round";
graph1.bulletColor = "#FFFFFF";
graph1.bulletBorderColor = "#01DCE3";
graph1.bulletBorderAlpha = 1;
graph1.bulletBorderThickness = 2;
graph1.bulletSize = 2;
graph1.lineThickness = 2;
graph1.lineColor = "#01DCE3";
graph1.balloonText = "<b>[[title]]:</b>[[value]]";

graph1.useDataSetColors = false;
stockPanel.addStockGraph(graph1);

// Define Stock legend
var stockLegend = new AmCharts.StockLegend();
stockLegend.valueTextRegular = " ";
stockLegend.markerType = "none";
stockPanel.stockLegend = stockLegend;

CHART.panels = [stockPanel];

// Other Settings
var scrollbarSettings = new AmCharts.ChartScrollbarSettings();
scrollbarSettings.graph = graph1;
scrollbarSettings.updateOnReleaseOnly = false;
CHART.chartScrollbarSettings = scrollbarSettings;

var cursorSettings = new AmCharts.ChartCursorSettings();
cursorSettings.valueBalloonsEnabled = true;
cursorSettings.categoryBalloonDateFormats = [{
   period : "YYYY",
   format : "JJ:NN:SS, DD MMMM"
}, {
   period : "MM",
   format : "MMM, JJ:NN:SS, DD MMMM"
}, {
   period : "WW",
   format : "JJ:NN:SS, DD MMMM"
}, {
   period : "DD",
   format : "JJ:NN:SS, DD MMMM"
}, {
   period : "hh",
   format : "JJ:NN:SS, DD MMMM"
}, {
   period : "mm",
   format : "JJ:NN:SS, DD MMMM"
}, {
   period : "ss",
   format : "JJ:NN:SS, DD MMMM"
}, {
   period : "fff",
   format : "JJ:NN:SS, DD MMMM"
}];
CHART.chartCursorSettings = cursorSettings;

var panelsSettings = new AmCharts.PanelsSettings();
panelsSettings.creditsPosition = "bottom-right";
panelsSettings.mouseWheelZoomEnabled = true;
panelsSettings.marginRight = 16;
panelsSettings.marginLeft = 16;
CHART.panelsSettings = panelsSettings;

// PERIOD SELECTOR ///////////////////////////////////
var periodSelector = new AmCharts.PeriodSelector();
periodSelector.position = "bottom";
periodSelector.dateFormat = "DD.MM.YYYY";
periodSelector.hideOutOfScopePeriods = false;
periodSelector.fromText = "De:";
periodSelector.toText = "À:";
periodSelector.inputFieldsEnabled = false;
periodSelector.periods = [{
   period : "hh",
   count : 1,
   label : "1 heure"
}, {
   period : "DD",
   count : 1,
   selected : true,
   label : "Un jour"
}, {
   period : "DD",
   count : 7,
   label : "1 semaine"
}, {
   period : "MM",
   count : 1,
   label : "MAX"
}];
CHART.periodSelector = periodSelector;

// Write Chart in Div Tag
CHART.write('main_chart');`

I am missing something here? Let me know about it.
Thank you

**Comment by qalbit** [comment]
I got the solution for this issue.

**Comment by massimilianochiodi** [comment]
Hello, What solution did you adopt? can you share
