### ISSUE TITLE
Exported PNG/JPG images does not have the same quality as SVG one

### ISSUE THREAD

**Issue by HaythemJ** [amcharts/amcharts3#225]
After exporting the chart as PNG/JPG, the result image does not have the same quality as the chart or as the exported SVG. The PNG/JPG format seems blurred.

Is there a export setting to enhance the quality?

**Comment by martynasma** [comment]
Try setting `scale` in image options:

https://www.amcharts.com/docs/v4/concepts/exporting/#Setting_options

**Comment by HaythemJ** [comment]
Thank you @martynasma 

I used this:
`this.toPNG({
                        multiplier: 2
                    }, function (base64) {             
                    });`
