### ISSUE TITLE
Different color for the x axis label

### ISSUE THREAD

**Issue by senocak** [amcharts/amcharts3#253]
This is my datas from backend
![Ek Açıklama 2020-07-01 135710](https://user-images.githubusercontent.com/6429176/86236478-d0c6b180-bba2-11ea-99ac-6f157ad80a2f.png)
this is my x axis but coloring is not working

![Ek Açıklama 2020-07-01 135710](https://user-images.githubusercontent.com/6429176/86236554-f05dda00-bba2-11ea-8a66-65fe48d5fd67.png)
this is the result

![Ek Açıklama 2020-07-01 135710](https://user-images.githubusercontent.com/6429176/86236600-066b9a80-bba3-11ea-9181-1d58df70a3e7.png)

**Comment by xorspark** [comment]
Looking at your chart screenshot and code, you're using [amcharts4](https://github.com/amcharts/amcharts4/). This repo is for amcharts3 related issues. Please post your question there.
