### ISSUE TITLE
How can I set a different field for tooltips in a PieChart?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts3#258]
I am looking for a way to handle negative values in a pie chart. My chart data looks like this bellow: 

```
data = [{
   name: 'Category A',
   value: 10,
   realValue: -10,
}];
```

I need to use the `value` field as chart value but `realValue` field to show tooltips

**Comment by xorspark** [comment]
You can directly reference the field in balloonText by name, e.g. `balloonText: "[[realValue]]"`

**Comment by gagigante** [comment]
@xorspark this attribute exists at version 4?

> You can directly reference the field in balloonText by name, e.g. `balloonText: "[[realValue]]"`

This attribute exists at version 4?

**Comment by gagigante** [comment]
> You can directly reference the field in balloonText by name, e.g. `balloonText: "[[realValue]]"`

Does this attribute exist in version 4?
