### ISSUE TITLE
How to make the charts render faster

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#26]
Hi,

I am working with ~ 3-5 MB of data (Stock OHLC Data for last 10 years) along with multiple axis etc.  Currently, my amcharts are rendered in 6-9 seconds.  

I am working with 1 GB RAM, Chrome browser and the free version of amCharts

Please suggest ways to optimize the render time.  I would ideally need the charts to render in 1-3 seconds.  I am willing to upgrade my server and purchase the licensed version of amCharts if that helps me achieve the speed that I am looking for.

Thank you
SD

**Comment by martynasma** [comment]
That sounds like a lot of data for a simple serial chart. I suggest implementing some sort of drill-down/incremental load scenario. You show aggregated info first. When user zooms in you load more granular data for that specific period.

We're currently working on the update to Data Loader plugin which would do that out of the box. I expect a release next week.

https://github.com/amcharts/dataloader

**Comment by debsush** [comment]
Was wondering if a high performance server will make the difference.  Please note that the rendering time I am mentioning is exclusive of the time it takes to load the data.  My data is pre-loaded and the 
5-8 seconds is the time to just form the charts out of the already loaded data set

**Comment by martynasma** [comment]
I don't think server performance is a factor here. Parsing so much data on client-side will take up most of the processing time.

**Comment by debsush** [comment]
Wonder how google charts or other stock charting libraries are able to render multiple stocks having ohlc data for 15-20 years (must be > 8 GB) in less than a second. Is there a trick that I am missing here

**Comment by debsush** [comment]
I think I have a trick to only import daily data when zoomed.  Whenever the zoomed event is triggered, my script calls a function which imports only a subset of data depending on event.startDate and event.endDate,  However, when the data gets updated, my chart is re-rendered which calls the render event.  Now when render event is triggered, I would like to call the zoom function and pass the last "zoom" event startDate and endDate.  Is this doable?

**Comment by martynasma** [comment]
Try setting `panelsSettings.zoomOutOnDataUpdate` to `false` to retain the same zoom position after data update.

**Comment by debsush** [comment]
Hi, I do not find this option in Amstock rather it is only available in AmserialChart

**Comment by martynasma** [comment]
OK, I think I'm starting to miss the point here. Stock Chart will try to retain the same zoom selection if you update the data and then call `validateData()`. Are you doing something else besides those two?

**Comment by debsush** [comment]
Let me try and explain.  I am using AmCharts to initially load monthly data (beginning of month prices).  When user uses the period selector/scrollbar/mouse to zoom into a period < 365 days, I use the Listener to fire a script outside of Javascript (in R and is not relevant for your review) to load the daily data for that period.

It seems when amCharts are rendered, the "zoom" event gets fired first followed by the "rendered" event.  So, my logic uses both these events to build the effect. See below

addListener('zoomed' , 'function(event) {

                    if ( typeof renderflag === "undefined" || renderflag === null ){
                    renderflag=0;
                    }

                    var start = event.startDate;
                    var end = event.endDate;
                    var timeDiff = Math.abs(end.getTime() - start.getTime());
                    var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24)); 
                    
                    if (diffDays<365 && renderflag==0 && document.getElementById("ZoomST").innerHTML != "+"){
                    document.getElementById("ZoomST").innerHTML = start;
                    document.getElementById("ZoomEND").innerHTML = end;
                    renderflag=1;
                    Shiny.onInputChange("zoomstart", start);
                    Shiny.onInputChange("zoomend", end);
                    //This is the cmmand that fires the R script to load the daily data into a data frame and then onto the Data Provider.  In short, this part fires a R function to load the daily data and rebuilds the amChart.  So again the "zoom" and "render" event gets fired within Javascript after the daily data has been loaded//
                    } else if (diffDays<365 && renderflag==0 && document.getElementById("ZoomST").innerHTML == "+"){
                    document.getElementById("ZoomST").innerHTML = "-";
                    document.getElementById("ZoomEND").innerHTML = "-";
                    } else if (diffDays>365 && renderflag==0) {
                    document.getElementById("ZoomST").innerHTML = "-";
                    document.getElementById("ZoomEND").innerHTML = "-";
                    } else {
                    renderflag=0;
                    }
                    
         }'),
        addListener('rendered' , 'function(event) {
                    var tempo = document.getElementById("ZoomST").innerHTML;
                    if (tempo != "-" && tempo != "+") {
                    var startdt = new Date(document.getElementById("ZoomST").innerHTML);
                    var enddt = new Date(document.getElementById("ZoomEND").innerHTML);
                    document.getElementById("ZoomST").innerHTML = "+";
                    document.getElementById("ZoomEND").innerHTML = "+"; 
                    renderflag=0;
                    event.chart.zoom(startdt, enddt);
                    }
        }'),

It works as long as I set maxSeries = 0 but is a clumsy hack in my opinion.

Is there more neat solution.  Also, can I direct the amChart not to fire the "zoom" event when rendering the chart.  I want the "zoom" event to get fired only when user specifically uses the period selector/mouse/scrollbar to zoom or when I categorically fire chart.zoom(startdt, enddt) command.

Thank you as always for your help

**Comment by martynasma** [comment]
No, I'm afraid there's no way to disable initial `zoomed` event. The chart will always do that. The only workaround is to ignore this event until `rendered` event fires.

**Comment by debsush** [comment]
How do I build a logic which will bypass the zoomed event until the rendered event fires.  I mean how to make the above logic I have provided more refined and efficient.

The above code works for sure but needs some expert opinion

**Comment by martynasma** [comment]
You can have some sort of flag which would indicate if rendered event has already fired.

```
addListener( 'zoomed', function( event ) {
  if ( event.chart.renderedFired !== true )
    return;

  // ...
} );

addListener( 'rendered', function( event ) {
  event.chart.renderedFired = true;

  // ...
} );
```

**Comment by debsush** [comment]
Excellent!!!

**Comment by debsush** [comment]
@martynasma You mentioned the new release to the data loader will be able to handle the below:

"That sounds like a lot of data for a simple serial chart. I suggest implementing some sort of drill-down/incremental load scenario. You show aggregated info first. When user zooms in you load more granular data for that specific period.We're currently working on the update to Data Loader plugin which would do that out of the box. I expect a release next week."

Do we have a demo of the new functionality.  Thank you
SD

**Comment by martynasma** [comment]
Unfortunately, that update got shelved as some more pressing matter took priority. We'll resume the development at some time soon, though. Just can't say when :(

**Comment by debsush** [comment]
Hi,

I am trying to load limited data to allow faster rendering of teh chart for the first time and load incremental data into the chart on pushing a button. 

If I have a dataset in my amStockChart , how can I add more data elements into the existing chart.dataSets[0].dataProvider.  My new data elements are in aJson "NewDF"

I tried chart.dataSets[0].dataProvider.push(NewDF);  but it did not work.  I am sure I am doing something fundamentally wrong here.  Appreciate your help

Regards
SD

**Comment by dan-da** [comment]
shoot!  I really need that functionality.  This seems like something most every serious stock display application (or anything with a large dataset) would need.  hopefully I can hack something together, but was hoping it would work out of the box.

> Unfortunately, that update got shelved as some more pressing matter took priority.

**Comment by debsush** [comment]
I was wondering if something like below can be done conceptually until the release.  (I have never tried it)

We load say the daily data for last 10 years at one go and in the post processing parameter aggregate the data into a higher period before passing it onto the data set

 "dataLoader": {
        "url": "data/MSFT.csv",
        "format": "csv",
        "showCurtain": true,
        "showErrors": true,
        "async": true,
        "reverse": true,
        "delimiter": ",",
        "useColumnNames": true,
         "postProcess": function(data, options) {
                                                if (data === null) {
                                                data = [];
                                                options.chart.addLabel("50%", "50%", "No Data Available");
                                                 } else {
                                                 data = aggergatedata(data,chart.startDate,chart.endDate);   
                                                 }
                                                 return data;
                                     }
          }

We now define an aggregation function here.  
I am currently trying to find a nice OHLCV aggregator function that I can run on top of my initial data which is fairly large.  
Thoughts?

**Comment by dan-da** [comment]
well, in my case, the goal is to be able to display data at whatever level of granularity the user desires.  So it could be minutes, hours, days, weeks, months, years, even decades I guess.  Clearly we cannot load decades worth of data a minute granularity into the browser.  So the idea is to associate timespans with granularity levels.  So for example if the chart is zoomed to 1 day, then we can show minutes.  If 1 week, then hours.   If 1 month, then days.  If 1 year then weeks or months.   This way we are always loading a reasonable amount of data from the server.

highcharts has a nice writeup of the problem and a [demo](http://www.highcharts.com/news/48-loading-millions-of-points-in-highcharts) that does this with supposedly 1.7 million data points.  Well actually they just send a date range to the server and let the server figure out the granularity.  Anyway, it works quite smoothly.

I have been trying to achieve something like that with amcharts by listening for zoom and periodSelector change events, but its not working right, and I've given up on that for now.  If you guys can create an amcharts candlestick+volume example that works like the highcharts example above, that would be really great and I'm sure a lot of people would use it.

**Comment by martynasma** [comment]
I understand. And we will most certainly resume the implementation of the plugin, especially that good chunk of it is already implemented. (before you ask, no it's too early to share :)

If it helps, it is centered around "zoomed" event, which uses built-in chart's granularity determining mechanism, then checks if we have the data for the selected period and at current granularity available. If not, it loads the missing data.

HC's example is nice, but it doesn't do omptimizations, like chunked caching (so the data that was loaded before does not get loaded again). It just loads appropriate data on every load.

**Comment by dan-da** [comment]
@martynasma awesome!  one more related area that I think could use improving or maybe I just don't understand amcharts:  when my dataset contains very few points eg for candlesticks, they get zoomed in and giant.  What I would like to do is tell the chart for example: hey display a graph for the entire month of June even though there is only one data point on June 23 in the entire dataset.  Otherwise, it seems that one must resort to creating fake start/end data rows.

**Comment by martynasma** [comment]
Sorry, missed your reply.

How about trying out this plugin?

https://github.com/amcharts/tools/tree/master/datePadding

**Comment by EmileIndik** [comment]
Any update on the issue @dan-da was having, regarding auto calculation of granularity for large datasets? Is this still on the table as a dataloader feature?
Thanks!

**Comment by martynasma** [comment]
@EmileIndik Not yet. Sorry.

**Comment by JEGardner** [comment]
Hi @martynasma, any update now? Would be a great feature.

**Comment by martynasma** [comment]
@JEGardner this is a long thread encompassing a lot of stuff. Which particular issue are you referring to?

**Comment by Guziq** [comment]
Hey @martynasma, been wondering if it's possible to present data with **maximum period** option?
 For example, I need to be able to preview 1M samples and rendering only 1000 samples at once is just fine for me.

**Comment by martynasma** [comment]
@Guziq You can use [`maxSelectedSeries`](http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#maxSelectedSeries) for that.

However, 1M data pints sounds like still too much for a Serial Chart. It will probably take a long time for it to initialize.

**Comment by gitolog** [comment]
Forced layout reflow is bottleneck of chart zoom
![devtools - localhost_3000_report_14_react_perf 2018-06-20 22 56 26](https://user-images.githubusercontent.com/8101401/41681421-3bdd1e00-74dd-11e8-9971-f9c8f0091fc5.png)
. getBBox method asks chart elements fo their dimensions and so browser begins to recalculate DOM. For every element of chart.

**Comment by Mamathatg** [comment]
Hi,
    I am plotting a serial graph of 44800 points. It takes around 80 sec to render the plot which i more for our requirement . I compared the plots using dataProvider and also dataLoader. Both takes same time approximately, Is there any other option where i can reduce the amount of time it takes to plot.

**Comment by wriozumi** [comment]
Try to remove animations, it worked for me.

**Comment by nasreddineskandrani** [comment]
@42b883  thanks ! I was having a loading logo freeze for 10 sets of data of 4000 points in  the same chart (multiline chart). After removing the animation with   
`lineSerie.showOnInit = false;` it's FAR better.
