### ISSUE TITLE
XY chart sometimes fails with error "... isRolledOverBullet ..."

### ISSUE THREAD

**Issue by dizel3d** [amcharts/amcharts3#28]
Sometimes XY chart fails during creation with error "... isRolledOverBullet ...". I have the problem in 3.19.6 and 3.20.3, but not in 3.18.6.
![image](https://cloud.githubusercontent.com/assets/593571/14531727/28791570-0267-11e6-82b0-a2b4c2d973aa.png)

**Comment by martynasma** [comment]
Is that any XY chart or some particular one? Any chance of getting your chart config and data so we can test?

If you want to keep it private, you can reach us at contact@amcharts.com
