### ISSUE TITLE
Using amcharts3 together with humanize-plus breaks charts

### ISSUE THREAD

**Issue by Maarius** [amcharts/amcharts3#29]
Please follow these steps to reproduce:

1. Make sure to have node.js installed
2. clone repo: https://github.com/Maarius/ember-amcharts-humanize
3. run "npm install"
4. run "bower install"
5. run "ember s"
6. open http://localhost:4200

Normally you should see a Pie Chart and a Line Chart, with the code taken straight from the examples.
However, as the library "humanize" from https://github.com/HubSpot/humanize is included, the charts are broken, e.g.
- if you hover the piechart, you see errors like "Uncaught TypeError: Cannot read property 'wedge' of undefined" in the console
- animations are not working
- the line chart is not shown at all

In order to show that humanize-plus causes the error follow these steps:
1. cancel "ember s"
2. open the file "ember-cli-build.js"
3. comment out the line "app.import('bower_components/humanize-plus/dist/humanize.js');"
4. run "ember s" again
5. the charts are working normally

Versions:
amcharts3: 3.20.2
humanize-plus: 1.8.1
ember: 2.4.3

Update: This issue is not restricted to ember.js!

If you clone https://github.com/Maarius/amcharts-humanize and open index.html, you'll see that it is broken as well.

**Comment by Maarius** [comment]
The version 1.5.0 of humanize does not cause these problems (see updated repo).

**Comment by martynasma** [comment]
Alright. So it's all set then?

**Comment by Maarius** [comment]
Well, everyone who installs amcharts and humanize-plus through bower will run into that problem because bower will use version 1.8.1 of humanize-plus.

**Comment by martynasma** [comment]
So the latest version has the issue?

**Comment by Maarius** [comment]
I am not entirely sure what counts as latest version. If you open https://github.com/HubSpot/humanize/releases you see that they list 1.5.0 as latest release. However, as I said, if you install through bower you'll get 1.8.1 (the one that causes problems).

**Comment by martynasma** [comment]
Found this in their code:

```
var isNaN = function isNaN(value) {
  return value !== value;
}; // eslint-disable-line
```

Looks like they are overwriting standard JS functions.

Sorry, can't help with this. I suggest you take it up with them. It's not very polite to override standard functions other libraries might be dependent on.
