### ISSUE TITLE
Amcharts is out of the container border. Why?

### ISSUE THREAD

**Issue by prostoandrei** [amcharts/amcharts3#30]
Some screenshot. Can't find way to fix it

![80575b0520](https://cloud.githubusercontent.com/assets/7234499/14734563/e73b545c-0873-11e6-879c-af3f9ba57b04.jpg)

**Comment by martynasma** [comment]
Try adding the following line of code **before** any other chart code:

```
AmCharts.baseHref = true;
```

**Comment by prostoandrei** [comment]
Wow. So easy.
Thank you @martynasma !
