### ISSUE TITLE
Publish the package on NPM

### ISSUE THREAD

**Issue by tacone** [amcharts/amcharts3#31]
Many of us are replacing bower with npm even for client packages. Alas amcharts3 is not officially released on npm (I only found an unofficial outdated package).

I think publishing on npm would be a good idea.

**Comment by mf085** [comment]
Hi tacone, you will find it here: https://www.amcharts.com/download/

**Comment by tacone** [comment]
Fantastic, thank you.

**Comment by iddan** [comment]
Hey there, we at @500tech using amcharts/amcharts3-react. We were surprised to discover that the latest version requires including this package in the page's script instead of `require()`-ing it to the bundle. Could you please explain why must it be required with a script tag

**Comment by Pauan** [comment]
Hi @iddan,

Please see [this comment](https://github.com/amcharts/amcharts3-react/issues/41#issuecomment-293155215) for an explanation about the change.
