### ISSUE TITLE
Is it allowed to put the free version of amcharts.js in a public github repo?

### ISSUE THREAD

**Issue by cuipengfei** [amcharts/amcharts3#32]
I am not sure how to interpret the linkware license, so is it allowed to put the free version of amcharts.js in a public github repo?

**Comment by martynasma** [comment]
Yep. It's tot fine.

Thanks for checking.

**Comment by cuipengfei** [comment]
Thanks for your response

**Comment by cuipengfei** [comment]
I am reopening this issue to add additional information.

The public repo that I am putting amcharts in uses AGPL.

So I guess I would be redistributing amcharts under AGPL.

Would that be violating the following statement?
> You may not redistribute, sublicense or sell this program without written permission of Antanas Marcelionis, the author of amcharts software.

**Comment by martynasma** [comment]
Nope. It wouldn't. Go ahead :)

**Comment by cuipengfei** [comment]
Thanks you, I will close this issue.
