### ISSUE TITLE
Treemap Chart

### ISSUE THREAD

**Issue by m1dst** [amcharts/amcharts3#33]
Would love to see a treemap chart.

https://en.wikipedia.org/wiki/Treemapping

**Comment by martynasma** [comment]
Maybe in the next major version later this year.

**Comment by mg1075** [comment]
+1

**Comment by m1dst** [comment]
How can you close the issue if it hasn't been added?  It might give people the impression you've done it or decided not ever to do it.

**Comment by martynasma** [comment]
Sorry if this introduced some sort of confusion.

Well, similarly it might give the impression that it will. This feature most certainly will not be implemented in the V3 (the version this repo is for), hence closed issue.

It will most certainly be implemented in the next major version (V4), as I mentioned before. Unfortunately, there's not a lot of details that I can provide right now.

I hope that clears this.
