### ISSUE TITLE
connect: false in radar chart doesn't work

### ISSUE THREAD

**Issue by rubenstolk** [amcharts/amcharts3#35]
https://live.amcharts.com/0NDJi/edit/

**Comment by martynasma** [comment]
Hi there,

Try instead of empty strings, use `null` character. Should do the trick.

https://www.dropbox.com/s/ci0ibh7fl9lj3v4/chrome_2016-05-12_22-07-31.png?dl=0

**Comment by rubenstolk** [comment]
Right... got it.
