### ISSUE TITLE
Amcharts watermark shows through non-transparent balloon

### ISSUE THREAD

**Issue by PowerGamer1** [amcharts/amcharts3#37]
I made serial chart balloon non-transparent (by setting balloon.fillAlpha to 1) and it displays properly with regard to graph grid, bars, etc (see first screenshot). But when balloon is drawn over the Amcharts watermark the watermark is shown through balloon background (as if balloon were transparent) yet the watermark is shown UNDER balloon's text (see second screenshot). This is probably a bug.

![ok](https://cloud.githubusercontent.com/assets/8275897/15268697/3a3981a0-19f0-11e6-936b-1774c850d6a9.png) ![overlap](https://cloud.githubusercontent.com/assets/8275897/15268698/3a3ae89c-19f0-11e6-89c7-c7ee160b9aed.png)

**Comment by martynasma** [comment]
Thank you for bringing this to our attention. We'll look for ways to fix this.

Meanwhile, I suggest you move the watermark to some other corner where it's a bit less prominent.

Use `creditsPosition` for that:

http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#creditsPosition

**Comment by martynasma** [comment]
I'm afraid we won't be able to fix this. The credits element is a div on top of the SVG. There's no way to make it go under certain elements within SVG. Sorry.
