### ISSUE TITLE
Multiple Axes StockChart

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#39]
Hi,

If I have a StockChart with multiple axes (one on the left side and other on the right), is it possible to ensure that the valueLineBalloon only shows the value of the right axis and not the left axis?

I have seen the code 

"valueAxes": [{
  // ...
  // value balloons are shown
}, {
  // ...
  "balloon": {
    "enabled": false
  }
  // value balloons are not shown
}]

Appreciate if we could also have a live demo available for our reference

Regards
SD

**Comment by martynasma** [comment]
Here's an example of a Stock Chart with multiple value axes and value line balloons:

http://codepen.io/team/amcharts/pen/fcd1fed3cb6487c27f357a15467f250c

To disable a balloon for some value axis, simply set it's `balloon.enabled` option to false. I.e.:

```
{
  "id": "a2",
  "axisColor": "#FCD202",
  "position": "left",
  "offset": 50,
  "balloon": {
    "enabled": false
  }
}
```

**Comment by debsush** [comment]
Thank you
