### ISSUE TITLE
Query about fillToGraph

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#40]
Hi,

I am unable use fillToGraph feature when comparable = TRUE.  I am trying to plot bollinger bands on a stockchart with stock price as the main chart while all other studies will form the comparing charts.  Please let me know if we can have something like compareFillToGraph so that I can fill the gap between two comparing charts (up and down of a Bollinger Band).  should I use the compareGraph property and lay out fillToGrpah as an argument in it.  Appreciate an example where it has been used when comparable=TRUE

Also, if I have two Base (one at 70 and one at 30) for a stockGraph, I can use negative Base property to color the area below 30 with a given color.  How can I color the area above 70 with a different specific color? 

Thank you
SD

**Comment by martynasma** [comment]
The idea of the `fillToGraph` is that you need to set the correct id of the graph. The id of the compared graph is constructed this way:

comparedGraph_[graph id]_[data set id]

So make sure you have `id` set for both graph and data set, so that you have a predictable id to set `fillToGraph` with.

Here's an example:
http://codepen.io/team/amcharts/pen/cd819da9d2e12b600ef91bb23756f4bb

**Comment by debsush** [comment]
Thanks.  Small edit to the example scenario.  Instead of filling the area between the main stockgraph and the compared stockgraph, I want to fill the gap between two compared stockgraphs.  So there are 3 stockgraphs - 1 main and other two are compared.  And I want to fill the gap between the two compared stockgraphs.  

StockGraph 1 (Main) - id= S1, Dataset = D1
StockGraph 2 (Compared) - id= S2, Dataset = D2
StockGraph 3 (Compared) - id= S3, Dataset = D3

I want to now fill the area between S2 and S3.  How would I do accomplish this. Thank you
SD

**Comment by martynasma** [comment]
Then the `fillToGraph` should need to go into `compareGraph`:

```
    "stockGraphs": [ {
      "id": "g1",
      "valueField": "value",
      "comparable": true,
      "compareField": "value",
      "lineThickness": 3,
      "balloonText": "[[title]]:<b>[[value]]</b>",
      "compareGraph": {
        "lineThickness": 3,
        "balloonText": "[[title]]:<b>[[value]]</b>",
        "fillAlphas": 0.5,
        "fillToGraph": "comparedGraph_g1_ds3"
      }
    } ]
```
