### ISSUE TITLE
Provide unminified version?

### ISSUE THREAD

**Issue by kewisch** [amcharts/amcharts3#41]
Hello amcharts. It seems you are only providing the minified/obfuscated version of amcharts publicly. Is this for business reasons, or simplicity? I have a developer that would like to use amcharts in a Firefox add-on, but for that to work the AMO reviewers need to look through the source code for potential security issues, especially when used within the add-on context.

Would it be possible to provide the unminified sources, if only to Mozilla reviewers?

**Comment by kewisch** [comment]
As an additional note, we also need instructions to reproduce the obfuscation, to verify the sources actually match with the release.

**Comment by martynasma** [comment]
At this time we provide unminified version only to OEM customers. So yes, it's for business reasons.

That being said, we'd like to discuss this plugin stuff with you. Can you reach out to us on contact@amcharts.com? Mention this thread so that it gets assigned to the right person.

Thanks!
