### ISSUE TITLE
Proper CommonJS/ES2015 support?

### ISSUE THREAD

**Issue by iamricky** [amcharts/amcharts3#42]
This topic has been broached [previously](https://github.com/amcharts/amcharts3/issues/20) but the lack of out-the-box support for ES6 module imports, has been a hindrance to setting up amcharts in a React/Babel/Webpack environment. Two ideal examples would be:

e.g. `import { amcharts, ammaps } from 'amcharts3';`
or
e.g. `import amcharts { serial, radar, pie, funnel } from 'amcharts3';`

The scant few workarounds I was able to dig up are a bit more [convoluted]( https://github.com/amcharts/amcharts3/issues/9) than generally acceptable.

**Comment by martynasma** [comment]
I understand your inconvenience.

We have started some work in that direction. However, it's moving quite slow as some other priority stuff is getting in the way.

We'll get there, though. Just can't say when :( unfortunately.

**Comment by iamricky** [comment]
@martynasma Completely understandable. In the interim, is there a non-trivial way of utilising AmCharts in a React/Node env?

**Comment by martynasma** [comment]
Sorry, didn't notice your comment. No, not that I'm aware of. Sorry.

**Comment by iamricky** [comment]
Hi @martynasma I ended up switching to highcharts. Sorry but the setup was less cumbersome.

**Comment by martynasma** [comment]
No worries. Thanks for the update.
