### ISSUE TITLE
AmchartsV3 dates cannot parse in firefox

### ISSUE THREAD

**Issue by Ewan-GrandSlam** [amcharts/amcharts3#43]
It seems dates do not properly parse in firefox, setting "parseDates" (via. the snippet below) causes graphs to not be rendered.

```
"categoryAxis": {
    "parseDates": true
}
```

It appears that no errors happen immediately, however after some time I noticed an error pop up along the lines of the following:

```
a is undefined (serial.js)
```

**Comment by martynasma** [comment]
Do you perhaps have your dates as strings in data?

If that is the case, you also need to set `dataDateFormat` so the chart knows how to parse it:

http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#dataDateFormat

Without it, the chart relies on JavaScript native functions to parse string dates, which does not always work with all formats.
