### ISSUE TITLE
ChartCursor missing in serial charts

### ISSUE THREAD

**Issue by niraj315** [amcharts/amcharts3#44]
I have updated from 3.17.0 to 3.20.6 . But now Chart cursor is disappeared and mouse cursor is now drawing line on dragging on Chart. If I will disable `chart.export.capture`, It will working fine. See [here](http://stackoverflow.com/questions/37653985/serial-chart-in-amcharts-showing-different-beahaviour)

**Comment by martynasma** [comment]
Put a comment in on your SO question. Let's keep the conversation going there.

**Comment by niraj315** [comment]
Actual Issue: When I capture Chart, It is rendering a new chart with _<canvas>_ tag on top of Original Chart.  So I am seeing wrong chart. In jsfiddle this chart will be rendered below original chart.
