### ISSUE TITLE
Error on Exporting multiple charts on the page to a single PDF

### ISSUE THREAD

**Issue by frankito777** [amcharts/amcharts3#46]
I have just copied the example and used the latest version of AmCharts and the graphic starts gaining height and never stop.
With the files used in the example everything works like a charm.

http://www.amcharts.com/tips/exporting-multiple-charts-on-the-page-to-a-single-pdf/

**Comment by martynasma** [comment]
Hi,

Try setting the following setting in your chart config:

```
"autoResize": false
```

**Comment by frankito777** [comment]
Thanks for your response. With the latest version (3.20.8) the problem is fixed.
