### ISSUE TITLE
Can we make the From and To fields in Period Selector READ only

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#47]
I do not intend to have any period selector buttons and would like to control the chart period externally.  Yet I like the fact that "From" and "To" fields show the start and end dates of the current chart instance.  Can we make those two fields READ only.

**Comment by martynasma** [comment]
You can set `readOnly` attribute of the input fields when chart renders. Here's a demo:

http://codepen.io/team/amcharts/pen/ab4bcf41ce0ff27e48cc639c87c00180

**Comment by debsush** [comment]
Perfect!!!!  Classy
