### ISSUE TITLE
none.js theme is missing

### ISSUE THREAD

**Issue by iamricky** [amcharts/amcharts3#48]
I've created an AmSerialChart in a Node.js (read: npm) environment. I would like to [gracefully handle charts that have no data](http://www.amcharts.com/tips/gracefully-handle-charts-data/) but discovered that the 'none' theme is missing. Any clue where I can find this theme in npm?

**Comment by martynasma** [comment]
"none" theme is not required. Simply remove that JS include. It's just a leftover on some of the older demos.

I have removed it from the one you referenced for your convenience.

**Comment by iamricky** [comment]
Gotcha. Thanks for your help.
