### ISSUE TITLE
CSS in AmCharts guides

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#50]
Hi,

Does amCharts allow axis annotation like below snapshot?

As a workaround, I am trying to give my guide labels the look and feel like the snaphot below.  Since this is not a feature directly available in the current version, I was hoping to use CSS.  Was wondering if you could advise how to access the label of my guide.  I tried the below but it did not work
.amcharts-guide-[guide_Close].labels:{fill: blue;}

![image](https://cloud.githubusercontent.com/assets/15077449/16538699/357e449a-402c-11e6-8c87-e156ebe3f312.png)

**Comment by martynasma** [comment]
I'm afraid there's no way to apply background to guide labels, via config or CSS. SVG works differently from HTML. There's no way to make any element have a background. Sorry.
