### ISSUE TITLE
Error bars are the wrong size

### ISSUE THREAD

**Issue by DanChaltiel** [amcharts/amcharts3#51]
You can see in this example : http://www.amcharts.com/tips/column-chart-confidence-intervals/

For instance, in 2009, 24.6+10=34.6, but the upper error bar is lesser than 30.

I have the same problem with my code, in an XY chart.

**Comment by martynasma** [comment]
This looks like a bug. Thanks.

Will let you know when the fix is available.

**Comment by DanChaltiel** [comment]
Thanks very much.
Great work BTW

**Comment by martynasma** [comment]
On the second look, everything seems to be OK. The error value is a total value of the error bullet, not in both directions from the center.

So 24.6 + 10/2 = 29.6 which seems to be right.

Makes sense?

**Comment by DanChaltiel** [comment]
Actually, when you put error bars, you usually present yours data as value+/-error.
But if it's stated and it works, then I guess it will be alright :-)
