### ISSUE TITLE
Cannot set step in an Axis

### ISSUE THREAD

**Issue by DanChaltiel** [amcharts/amcharts3#52]
I have a XY chart, and my points are measured every 30 minutes.
For this reason, I want to set the step of my xAxis to 30.
For very surprising reasons, the [step ](https://docs.amcharts.com/javascriptcharts/ValueAxis#step) of ValueAxis is read-only.

I tried the tips written on https://www.amcharts.com/tutorials/user-defined-minmax-values-of-value-axis/, but changing gridcount and labelFrequency could only change step to 20 or 50, but no other value.

It seems wanted by the team, so maybe it's more a feature request.
I may ask why is it wanted if so ?

**Comment by martynasma** [comment]
The `step` is a calculated value, not a setting, hence it being read-only.

I'm afraid there's currently no way to force 30 min increments on a date-based value axis. The chart will kind of determine it by itself.

You can play around with another setting as well: [`minHorizontalGap`](http://docs.amcharts.com/3/javascriptcharts/ValueAxis#minHorizontalGap)

I hope this will help.

There are no immediate plans to implement a user-defined `step` setting.

Sorry.

**Comment by julianljk** [comment]
_"on a date-based value axis"_ is this **only** for date based values, or does this apply to number based values as well

**Comment by martynasma** [comment]
This goes for all value axes. The chart uses fuzzy logic to determine number of grids/values and thus increments.

As I mentioned previously you can play around with `minHorizontalGap` (or `minVerticalGap` for vertical axes) to maybe find a setting that suits your needs and produces increments that you require.
