### ISSUE TITLE
Pre-rendering amCharts server side

### ISSUE THREAD

**Issue by GoChartingAdmin** [amcharts/amcharts3#54]
I have been made to believe that client side pre-rendering of charts will improve the performance (atleast during initial load).  Is there a way we could do so using amCharts.  Appreciate some guidance and please excuse me if my queries are naive as I am trying to learn different ways of optimizing the performance of these wonderful amCharts on my website.

Reference: http://mango-is.com/blog/engineering/pre-render-d3-js-charts-at-server-side.html

Regards

**Comment by martynasma** [comment]
Hi,

I'm afraid we do not offer server-side pre-rendering option. Not sure if it would speed things up considerably.

I suppose as with everything else, there might be some situations where it could save some client-side time at the expense of the server CPU, and setups where it would not be noticeable or even have negative effect.

In any case, we do not have any immediate plans on implement this feature.

**Comment by jamalwsilva** [comment]
Server side rendering would be useful for downloadable reports, pdf, images, stylesheets, emailing, etc.
