### ISSUE TITLE
Is mouseWheelZoomEnabled feature available in amStockChart

### ISSUE THREAD

**Issue by GoChartingAdmin** [amcharts/amcharts3#55]
I know mouseWheelZoomEnabled as a feature is available in amSerial Chart but is it avaiable to amStockCharts. Although I could see the parameter under the amStockPanel Class, I could not make it work. Appreciate a fiddle which shows mouseWheelZoomEnabled being used in amStockCharts

I have seen the below example but could not use it in an amStockChart

https://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/

Regards SD

**Comment by martynasma** [comment]
Technically, yes:

```
"panelsSettings": {
    "mouseWheelZoomEnabled": true
  }
```

However, now that I'm testing it, it seems that there's a bug which makes the above setting make mousewheel to pan the chart rather than zoom.

We'll need to fix this.

Thanks for bringing it to our attention!

**Comment by martynasma** [comment]
Fixed in 3.20.10
