### ISSUE TITLE
amCharts with React

### ISSUE THREAD

**Issue by GoChartingAdmin** [amcharts/amcharts3#56]
Hi,

Below is an example of how HighCharts can be used with reactJS.  I am using amCharts in my app and was wondering if you could create a similar demo or documentation showcasing how could I use the amCharts in my app with react.

Reference: http://www.highcharts.com/blog/192-use-highcharts-to-create-charts-in-react

Appreciate your guidance.

Regards

**Comment by JakubKontra** [comment]
+1

**Comment by martynasma** [comment]
Guys,

Here's a better solution: https://github.com/amcharts/amcharts3-react
