### ISSUE TITLE
Group to Period query

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#57]
Hi,

The amCharts do a beautiful job of aggregating data into higher periods.  I am using amStockCharts and want to leverage the built-in algorithm with the only exception that I only want to produce a new data array which I can pass onto the dataProvider.

I have daily OHLCV (Open/High/Low/Close/Volume) data and I have an external button which when clicked should aggregate the daily data into weekly or monthly data and then pass onto the chart.mainDataSet.  Is there an internal function which will do this for me instead on me writing a function separately to aggregate the data?

var dailydata = //daily OHLCV json//
chart.mainDataSet.dataProvider = dailydata

onclick of the weekly button

var weeklydata = dailtToWeekly(dailydata) // Is there an amChart built-in function that I could leverage
chart.mainDataSet.dataProvider = weeklydata

PS:  I have currently no intention of changing either minPeriod or any other categoryAxis parameter as shown below
http://jsfiddle.net/amcharts/N2WeH/

The closest I got to was the example below but it is not suited to OHLCV data
http://www.amcharts.com/tips/dynamically-changing-data-granularity-serial-chart/

Appreciate your guidance.
Regards
SD

**Comment by martynasma** [comment]
There is no "public" amCharts function that you can use to aggregate data.

What exactly is wrong with the approach of setting `groupToPeriods` dynamically? I think it's quite elegant.

**Comment by debsush** [comment]
I agree it is elegant.  I will provide some more context around the objective and may be you can suggest a better way to achieve the same.

In my stock chart, first I am loading the daily OHLCV data and then computing some basic indicators like SMA using the data available in it

chart.dataSets[0].dataProvider = daily OHLCV data
chart.dataSets[1].dataProvider = indicatorfunction (daily OHLCV data)

Now if the user changes the period from daily to monthly, ideally the indicator should recompute using monthly data as against daily data.  So one way of doing it is on the server side, I convert daily OHLCV data to monthly data and then push it to the chart.  This is what I am doing now.

However, what would be nice is that the re-computation of both the main dataset and the indicator data set happens on the client side when the user changes the period

var newdata = daily_to_monthly(daily OHLCV data)
chart.dataSets[0].dataProvider = newdata
chart.dataSets[1].dataProvider = indicatorfunction (newdata)

Can you suggest if the in-built aggregation can achieve the above.  Please note that the indicator computation needs to be on monthly data now as against on daily data and then aggregated to a monthly view because I think both mean different things.

Regards
SD

**Comment by debsush** [comment]
Hi,

Can we have an smStock version of the below demo where the data is in OHLCV format and we use a generic function to convert it from one period to the higher period.

http://www.amcharts.com/tips/dynamically-changing-data-granularity-serial-chart/

This would help a lot of users like me.

**Comment by martynasma** [comment]
Sorry, missed your reply. (as I mentioned before GitHub is not monitored by support staff)

There's no externally usable aggregation functions. You'll need to implement your own.

Here's a very basic example:

https://www.amcharts.com/kbase/dynamically-changing-data-granularity-serial-chart/
