### ISSUE TITLE
Formatting the Last Candle

### ISSUE THREAD

**Issue by debsush** [amcharts/amcharts3#58]
Hi,

I am having a formatting issue with the last candle in my amChart - it gets clipped into half by the y axis on the right.

I had raised the query in stackoverflow but did not get any response back so I am posting it here.
[ Image Showing the Last Candle Issue](http://stackoverflow.com/questions/38408678/unable-to-view-the-complete-last-candle?noredirect=1#comment64236019_38408678)

As you can see in the pic below, only 50% of my last candle appears and I am having a hard time trying to figure out the settings which will make sure I can view the last candle in its entirety enter image description here.  If you look at the last candle in RED, you will see that the axis begins at midpoint of the last candle. If you compare this with below candle , you can fully view the last candle

http://jsfiddle.net/amcharts/TLx2n/

Key and relevant chart componenets are as follows:

```
graph = new AmCharts.AmGraph();
graph.id = "Price";
graph.title="Main";
graph.valueAxis = 'v1';
graph.showHandOnHover= true;
graph.proCandlesticks=  false;
graph.labels = true;
graph.balloonColor="#00000";
graph.comparable=true;
graph.openField="Open";
graph.highField="High";
graph.closeField="Close";
graph.valueField="Close";
graph.type='candlestick';
graph.fillAlphas= 0.7;
graph.lineThickness= 1;
graph.fillColors= '#CC0000';
graph.lineColor= '#CC0000';
graph.negativeFillColors= '#000000';
graph.negativeLineColor= '#000000';
graph.negativeLineAlpha= 1;
graph.negativeFillAlphas= 0.7;
graph.proCandlesticks= false;

var categoryAxis = chart.categoryAxis;
categoryAxis.axisAlpha = 1;
categoryAxis.groupToPeriods = ["DD", "WW","MM"];
categoryAxis.maxSeries=300;
categoryAxis.fillAlpha=.2;
categoryAxis.equalSpacing = true;
categoryAxis.parseDates = true; 
categoryAxis.startOnAxis = true;
categoryAxis.gridAlpha = 0.5;
categoryAxis.minorGridAlpha = 0.07;
categoryAxis.axisColor = "#000000";
categoryAxis.axisHeight=25;
categoryAxis.inside=false;
categoryAxis.tickLength = 0;
categoryAxis.gridThickness = 0;
categoryAxis.minorGridEnabled=false;
categoryAxis.axisThickness=0;
categoryAxis.gridThickness=0;

Other properties that I am using are as follows:
1. ValueAxesSettings

inside:false,
autoMargins:true,
minorGridEnabled: false,
logarithmic: false,
treatZeroAs: 0,
axisAlpha: 1,                                       
gridAlpha: 0, 
fillAlpha: 0,
minorGridAlpha : 0.07,
gridColor: "#000000",
axisThickness: 1,
gridThickness : 1,                                       
tickLength: 1,
minMaxMultiplier: 1
```
Please let me know if I have not been clear in articulating the pain point in visualizing the last candle in its entirety or have not provided enough details

**Comment by martynasma** [comment]
Hi,

Set `categoryAxis.startOnAxis` to `false`. This should do the trick.

Will reply on SO as well.

**Comment by debsush** [comment]
Awesome.  Thank you
