### ISSUE TITLE
AmCharts.ready() needed or not?

### ISSUE THREAD

**Issue by PowerGamer1** [amcharts/amcharts3#59]
The charts built by live editor https://live.amcharts.com/ do not create the chart inside a call to AmCharts.ready():
```HTML
<!DOCTYPE html>
<html>
	<head>
		<title>chart created with amCharts | amCharts</title>
		<meta name="description" content="chart created using amCharts live editor" />

		<!-- amCharts javascript sources -->
		<script src="http://www.amcharts.com/lib/3/amcharts.js" type="text/javascript"></script>
		<script src="http://www.amcharts.com/lib/3/serial.js" type="text/javascript"></script>

		<!-- amCharts javascript code -->
		<script type="text/javascript">
			AmCharts.makeChart("chartdiv",
				{
                                // ...
				}
			);
		</script>
	</head>
	<body>
		<div id="chartdiv" style="width: 100%; height: 400px; background-color: #FFFFFF;" ></div>
	</body>
</html>
```
The API Reference for AmCharts 3 (https://docs.amcharts.com/3/javascriptcharts/AmCharts) has no mention of AmCharts.ready() whatsoever.

On the other hand examples in this repo use AmCharts.ready(). Tutorial (https://www.amcharts.com/tutorials/your-first-chart-with-amcharts/) suggests that AmCharts.ready() method should be used.

So either Live editor produces incorrect code and AmCharts.ready() should be documented in API Reference or AmCharts.ready() is not needed and tutorials and examples here should be modified to remove a call to AmCharts.ready().

**Comment by martynasma** [comment]
Sorry for the confusion.

There are two ways to instantiate an amCharts chart:

1) Object-based (old). You are using `AmCharts.ready()` handler to create chart objects as well as create it using `write()` method.

2) JSON (new and recommended method). It uses `AmCharts.makeChart()` method which has it's own way to check for DOM readiness and therefore does not need `AmCharts.ready()`.

Some of the older examples, still use the old method. Most of the ones created within a year or so use JSON method.

I hope that makes sense.

**Comment by PowerGamer1** [comment]
Thanks for the explanation. Especially this should really be put somewhere in AmCharts docs:
 > 2) JSON (new and recommended method). It uses  AmCharts.makeChart()  method which has it's own way to check for DOM readiness and therefore does not need  AmCharts.ready() .

**Comment by martynasma** [comment]
Noted. Thanks!

**Comment by RickBross** [comment]
Just had to deal with a week of stress over this issue while working for an agency on a holiday project for a massive client.

If you're using the common js paradigm, you're probably not going to need .ready();

Also, @martynasma can you make sure that you dont have any demos with .ready()?

Any plans on making this a npm package? Can I collaborate and do that for you?

**Comment by martynasma** [comment]
Hi @RickBross,

Thanks for the suggestion.

Well, we have literally hundreds, if not thousands of demos assembled over the years. Some of those were created in a ".ready() era". It would be an overkill to go over all of them and redo everything.

We haven't created a single demo with `.ready()` for several years now.

And thank you for your offer on assistance with npm. We are actually working with npm team to take over all amcharts-related packages so that we maintain them. So far only "amcharts3" is stubbornly refusing to cooperate. We have all other packages taken over: amstock3 and ammap3.

Hopefully we will be able to resolve it with the help of npm team.
