### ISSUE TITLE
dist folder

### ISSUE THREAD

**Issue by maruilian11** [amcharts/amcharts3#6]
hi, we want to add your lib on https://cdnjs.com, because amcharts contains too many file, and it makes our auto-update config very complex and seems not so reliable. we hope you can create a dist folder, so we can add all files in it with simple config.
thank you very much!
https://github.com/cdnjs/cdnjs/pull/5747#issuecomment-154792551

**Comment by martynasma** [comment]
Hi,

We do have npm package file in the repo:

https://github.com/amcharts/amcharts3/blob/master/package.json

Or is there something else that you need to pull the files effectively?
