### ISSUE TITLE
Unable to identify the error when loading resources 

### ISSUE THREAD

**Issue by GoChartingAdmin** [amcharts/amcharts3#60]
Hi,

1/5 times my webapp throws out error when loading the amCharts resources.  It happens when loading the Export pluggin and as a result, certain chart functionalities are impacted.

Errors in the console
.....server path/amcharts-3.18.2/plugins/export/libs/pdfmake/pdfmake.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
.....server path/amcharts-3.18.2/plugins/export/libs/fabric.js/fabric.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
.....server path/amcharts-3.18.2/plugins/export/libs/jszip/jszip.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
.....server path/amcharts-3.18.2/plugins/export/libs/FileSaver.js/FileSaver.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
.....server path/amcharts-3.18.2/images/dragIconRoundSmallBlack.svg Failed to load resource: the server responded with a status of 404 (Not Found)
dragIconRoundSmallBlack.svg:1 GET http://.....server path/amcharts-3.18.2/images/dragIconRoundSmallBlack.svg 404 (Not Found)

Once that happens, svg icons fail to render and impacts the mobility of the tooltips etc.

Since it does not happen all the times and not in all systems, I am at my wits end on how to fix this.  Any guidance would be much appreciated.  

Regards

**Comment by martynasma** [comment]
That is a weird issue. Do you see any of that happening with any other resources than amCharts'?

I don't think this is related to Export plugin, because svg icons are affected as well.

Does this happen in all browsers?

**Comment by GoChartingAdmin** [comment]
I see this issue all the time when I open my app in my Samsung mobile.
It works fine in my home laptop which is running on Chrome.  But these errors throw up at times even in my office laptop which is running Chrome as well.  Is it device specific rather than browser specific.

I can provide the URL details in a private domain as I am not allowed to share it publicly at this point in time. Please let me know an email where I can provide you the details.

Appreciate your help on this.

**Comment by GoChartingAdmin** [comment]
Now I have a situation where I have mirrored my App.  One app is able to successfully load the resources while the other isn't. Is there a way by which I can direct the charts to the location of the resources specifically without relying on the servers and packages to do so

**Comment by GoChartingAdmin** [comment]
If I use the path = www.amcharts.com/lib/3/ in my chart, will it reference the latest version of the library which was released recently (3.20.10) or will it still be referencing the library version which I have installed in my server
