### ISSUE TITLE
What are the strategic new releases that we can expect in amStockChart

### ISSUE THREAD

**Issue by GoChartingAdmin** [amcharts/amcharts3#63]
Hi,

As I develop my app using amCharts, was wondering if you could give us a preview of the future roadmap as it relates to amStockCharts.  This will help me understand which componenets should I build natively and which should be left to amCharts library to manage

Some of the key fundamental features we look forward to are:
1. Performance boost using Canvas rendering etc.  I know HC tried something like below but not sure if amCharts have any future strategic plans out there
http://www.highcharts.com/news/175-highcharts-performance-boost
2. Adding discontinuous time scale charts like Renko, Kagi, Line Break and Point and Figure.  

I would be more than happy to contribute to the above dev efforts in any way I can.  Big fan of amCharts!!!!

Regards

**Comment by martynasma** [comment]
Hi there,

Thanks!

I'm afraid this is not the place to discuss this topic.

Could you please reach out to us on contact@amcharts.com?
