### ISSUE TITLE
Moving on the map without saving position

### ISSUE THREAD

**Issue by Laboratory** [amcharts/amcharts3#64]
Hello,

How can I save position after moving by mouse on the map? Right now after an update data, the map tries to move on the "strange" position.

This case works only for standard zoom https://www.amcharts.com/kbase/retaining-map-zoom-level-position-data-update/ and If you move the map by mouse and click to `Update map data` then you see how the map position returning to the desired.

Thx, V

**Comment by martynasma** [comment]
Thanks for the heads up.

Fixed the demo to retain the position as well.

**Comment by Laboratory** [comment]
it works
