### ISSUE TITLE
"labelRotation": auto

### ISSUE THREAD

**Issue by holmes1491** [amcharts/amcharts3#65]
is that possible ???

**Comment by martynasma** [comment]
Yes:

http://docs.amcharts.com/3/javascriptcharts/AxisBase#autoRotateAngle
http://docs.amcharts.com/3/javascriptcharts/AxisBase#autoRotateCount

Basically, if there are more labels than there are set in `autoRotateCount`, they will be rotated at `autoRotateAngle`.

This goes for horizontal axes only.

**Comment by holmes1491** [comment]
thanks man for prompt and humble reply ! (not mine)

actually done dumb thing to create issue for existed api...

by the way

Great Plugin

**Comment by martynasma** [comment]
No problem. Thanks.
