### ISSUE TITLE
Black chart with light theme

### ISSUE THREAD

**Issue by HaythemJ** [amcharts/amcharts3#66]
Hi,

I am using amcharts in my application. I am refering to amcharts js in the web but I am getting always black chart: 

```
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
<link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
```

![image](https://cloud.githubusercontent.com/assets/9905290/18258006/55731f38-73c5-11e6-96f6-11781e7f5a49.png)

What I am missing?

Best Regards
H.JAIDI

**Comment by martynasma** [comment]
I'm assuming you are using this demo:

https://www.amcharts.com/demos/css-animations/

It has colors set directly in chart config, which overrides theme colors. The theme will only apply colors if they are not explicitly set in config with settings like `lineColor`, `filColors`, etc.
