### ISSUE TITLE
legend value texts vertical positioning fails (overlapping each other) when using external div

### ISSUE THREAD

**Issue by maksuturvaict** [amcharts/amcharts3#69]
When legend is set as a part of a chart, legend row are distiributed nicely with equal vertical space even when some legend items wrap and need more text rows than the others. (http://jsfiddle.net/t740d2bq/)

But when the legend is set to an external div, the space between legend items is calculated correctly but is incorrectly set BEFORE the legend item. This causes long legend texts overlapping others and having extra space above them. (http://jsfiddle.net/b0Lz0ok1/)

**Comment by martynasma** [comment]
This looks like a bug. Thanks for the heads up.

We'll let you know when this is fixed.

**Comment by martynasma** [comment]
This was fixed in 3.20.14.

Sorry we somehow managed miss informing you. GitHub is not tied into our support system.
