### ISSUE TITLE
validateData breaks XY chart

### ISSUE THREAD

**Issue by dizel3d** [amcharts/amcharts3#7]
See an example http://jsfiddle.net/dizel3d/nrorjykc/. Steps for reproducing:
1. Zoom in right side of chart.
2. Call chart.validateData().
3. Now chart is broken.

**Comment by dizel3d** [comment]
Fortunately, there is a workaround http://jsfiddle.net/dizel3d/8g3he0kf/: call `chart.zoomOut()` before `chart.validateData()`.

**Comment by martynasma** [comment]
Just wanted to let you know that we are working on a fix.

Hopefully the new version which fixes this behavior will be out next week.

Thanks!

**Comment by iprotsyuk** [comment]
It seems that the issue was fixed in v.3.18.0. Thanks @martynasma!

**Comment by martynasma** [comment]
Great. Thanks for checking!

**Comment by dizel3d** [comment]
Now there is a new trouble: "Show all" button hides after `chart.validateData();`. See the same example http://jsfiddle.net/dizel3d/nrorjykc/.

**Comment by martynasma** [comment]
Indeed. Thanks for reporting!

**Comment by martynasma** [comment]
OK, turns out this has been already fixed in 3.18.1. Make sure you upgrade.

Here's a fiddle with the current version, working as expected:

http://jsfiddle.net/nrorjykc/7/

**Comment by dizel3d** [comment]
@martynasma, thank you!
