### ISSUE TITLE
Rendering Speed IE

### ISSUE THREAD

**Issue by cwburggrabe** [amcharts/amcharts3#70]
Hello,

My team and I have been developing a solution with amCharts to fill the gaps of other charting packages we have implemented. We noticed an issue where the charts will renders extremely slow in IE.

Here's a fiddle of my test: [Fiddle](https://jsfiddle.net/cwburggrabe/z25trt24/3/)

Chrome will render the charts almost instantly, while IE (Edge) will hang for about 300ms before completing the chart. The other charting package we use doesn't seem to lag as much, or at all.

Is this just a limitation by IE or am missing or introducing this behavior with some option for the charts.

Thank you for your help!

**Comment by martynasma** [comment]
Hi there,

That's weird. I'm getting identical results in both Chrome and Edge - around 200ms at least according to the debug clocker that you have set up there.

I also don't get visual delay on Edge either.

What do you get for Chrome?

**Comment by cwburggrabe** [comment]
Well, we figured out what the problem really was. It turns out it was the machines we are running on. The computers we received to develop on were all created from a shadow copy of another computer. So when we tested across multiple computers they ask had the same result.

So, no issue! Woohoo! :-D
