### ISSUE TITLE
legeng.periodValueText: "[[value.average]]" problem

### ISSUE THREAD

**Issue by mrspartak** [amcharts/amcharts3#73]
There is problem with rounding and display.
![Image](https://i.gyazo.com/ae8d35bf316fe370a80b545d2395e4b1.png)

**Comment by martynasma** [comment]
Have you tried setting [`precision`](http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#precision) setting on your chart?

**Comment by mrspartak** [comment]
Oh, that worked! Thanks a lot and sorry!

**Comment by martynasma** [comment]
You're welcome!
