### ISSUE TITLE
Realtime update

### ISSUE THREAD

**Issue by e-currencytrade** [amcharts/amcharts3#76]
Chart Zoom Selection is removed on real time update 

https://www.dc-ex.com/graph.html

**Comment by martynasma** [comment]
The chart should try to maintain current selection scope across data updates. I tried your chart and it does that. Did you fix it already?

**Comment by e-currencytrade** [comment]
it is not fixed. when we use "glueToTheEnd": true, the current zoom selection is remove.  provide example fiddle using this json https://www.dc-ex.com/loadjson.php we need the chart realtime time update

**Comment by martynasma** [comment]
This is a Stock Chart. Let's continue it in the appropriate thread:

https://github.com/amcharts/amstock3/issues/2
