### ISSUE TITLE
Gauge diagram won't appear when it is inside of Angular ng-repeat

### ISSUE THREAD

**Issue by srdjanristic** [amcharts/amcharts3#77]
My code is as following: 
`<div class="panel panel-primary">
       <div class="panel-heading">Correlations</div>
                <div class="panel-body"> 
                      <div ng-repeat="something in array">
                                <div id="gaugeDiagram"></div>
                        </div>
                </div>
       </div>
  </div>`

Gauge diagram does not appear for any of the elements, when I put it outside of ng-repeat element everything works, what am I doing wrong?

PS chart.invalidateSize(); does not solve it

**Comment by martynasma** [comment]
As far as I understand the `ng-repeat` repeats blocks inside it. You have a `<div id="gaugeDiagram"></div>` in it, which has a hardcoded fixed id. This might be ending up with a document with multiple instances of the containers with the same id, which is not right.

Maybe this helps.
