### ISSUE TITLE
Multi-level Pie Chart

### ISSUE THREAD

**Issue by christopherjbaker** [amcharts/amcharts3#78]
Love amCharts! I've been looking around, but I have been unable to find an answer to this query. Does amcharts support any kind of multi-level pie chart? Wherein each each item in the chart can be subdivided into more pieces.

I did some googling and found [this example](http://bl.ocks.org/mbostock/4063423), created with d3. I would certainly prefer to stick to a single library, however. If it doesn't support this, any chance this could turn into a feature request instead? XD

**Comment by martynasma** [comment]
Thanks!

I'm afraid we don't support nested donut charts. The only option is to place multiple separate donut charts over each other.

Here's an example:

https://www.amcharts.com/kbase/nested-donut-chart/
