### ISSUE TITLE
pdfmake.js is conflicted with underscore library

### ISSUE THREAD

**Issue by ambrous** [amcharts/amcharts3#79]
Hi.

My application are using backbone.js which based on underscore library (http://underscorejs.org/) and after loading pdfmake.js to page function from underscore.js is not found.

How can I isolate pdfmake.js?

**Comment by martynasma** [comment]
You may need to disable autoloading of Export plugin's dependencies and load them by yourself.

Here's more info:

https://github.com/amcharts/export#2-manual

**Comment by ambrous** [comment]
What should I do in case single page application?
For example, after first page load I add libs by adding `<script>` into page, then if I going to other page I am removing `<script>` with libs by 

`$('script.amcharts-libs').remove();`

but lib's code stayed in memory and I have error again.

Other way - adding underscore.js after removing export libs, but it is very bad way.

**Comment by martynasma** [comment]
I don't think you need to remove amCharts libs. You can disable auto-loading of the Export-related libs by setting `"libs": { "autoLoad": false }`:

```
"export": {
  "enabled": true,
  "libs": {
    "autoLoad": false
  }
}
```

Then you'd only need to load required libraries in your application, from the place and versions that you need.

**Comment by ambrous** [comment]
It is OK, but I need to use both libs in my application and now after loading export libs I can not use my libs.

**Comment by martynasma** [comment]
You might need to set up your application so that underscore loads **after** Export-related scripts, as this SO thread suggests:

http://stackoverflow.com/questions/35653999/pdfmake-conflicts-with-underscore

**Comment by martynasma** [comment]
You're welcome!
