### ISSUE TITLE
"Failed to execute 'toDataURL' on 'HTMLCanvasElement'" in a local web-page

### ISSUE THREAD

**Issue by iprotsyuk** [amcharts/amcharts3#8]
Hey guys,

Thank you so much for this wonderful library! Unfortunately, I faced a problem when working with it. Namely, I make some plots with amcharts on a local web-page, and I get the following error in Chrome when I try to export or print a plot image (using the export plugin):
`Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported. http://www.amcharts.com/lib/3/plugins/export/libs/fabric.js/fabric.js:678`.
It seems that a problem with fabric.js, not amcharts, but I'm not handy enough with canvas painting to figure it out. Could you please suggest any workaround for this that doesn't require moving my page to a web-server?

**UPD:**
[Here](https://www.dropbox.com/s/0yxbk6rfdeo9e28/amcharts_demo.zip?dl=0) you can find a small example where the problem is reproduced.

**Comment by martynasma** [comment]
This error means that you have an image loaded from different host than the web page itself ("tainted") OR you are loading this web page directly from the file system (file:///). Try loading it through web server. If the issue still persists, make sure that amCharts libraries are loaded from the same host as the web page displaying the chart itself.

**Comment by iprotsyuk** [comment]
Yes, I load the web-page directly from a file system. Actually, I'd like to embed amcharts into a native c++ app for graph visualization, that's why I'm looking for a solution without a web-server. Are there any options for this?

**Comment by martynasma** [comment]
That won't work I'm afraid, due to aforementioned browser security restrictions.

In this case you will need to embed your data as a JavaScript (JSON) code along the chart code.

I.e.:

```
var chartData = [{
  "category": "1",
  "value": 100
}, {
  "category": "2",
  "value": 110
}];

AmCharts.makeChart("chartdiv", {
  // ...
  "dataProvider": chartData,
  // ...
});
```

I hope this helps.

**Comment by iprotsyuk** [comment]
Yep, this is what I do, and everything works fine except the export plugin. I use qt webkit for html rendering, and I changed all its default security settings to allow working with local files, but it still gives me this security error.

Sorry for misleading you in the beginning. Chrome gives the same error with local files, and it uses webkit under the hood. As most of people are more familiar with chrome than qt webkit

**Comment by martynasma** [comment]
Well, I'm not sure about qt, but Chrome will never allow exporting the image when loaded locally. We're not aware of any workarounds, I'm afraid. Maybe it's not Chrome or qt, maybe it's the restriction of the rendering engine. I wish there was something more that we could do for you.

**Comment by iprotsyuk** [comment]
Alright, there's definitely a way to hack into html, pull an image out of canvas and pass it to the wrapping c++ code and save it afterwards. But of course, it would be easier for me to just use a working and tested solution. Thanks anyway.
