### ISSUE TITLE
Download Pic of Chart Behind Data

### ISSUE THREAD

**Issue by mpansky** [amcharts/amcharts3#80]
How do we move the download pic of data button from out of the chart or to an external button we could incorporate into our header? See picture below of example. Thanks

![image](https://cloud.githubusercontent.com/assets/14637417/20032792/4529e63e-a34f-11e6-9c8a-1015fa18491b.png)

**Comment by martynasma** [comment]
You can use Export’s `divId` setting:

```
"export": {
  "enabled": true,
  "divId": "exportdiv"
}
```

Here's a working demo:
https://www.amcharts.com/kbase/placing-export-menu-button-outside-chart/
