### ISSUE TITLE
Any zoom event to detect when user has completed zooming

### ISSUE THREAD

**Issue by coderkeku** [amcharts/amcharts3#81]
Does AmCharts expose any event to detect when user has completed zooming. Currently there is an event called **zoomed** which gets fired several times when the user moves the Zoom bar.
Or, is there anyother way to load new set of data when user zooms.

**Comment by martynasma** [comment]
No, I'm afraid.  You can disable actual zooming when user is dragging the scrollbar using `updateOnReleaseOnly`:

http://docs.amcharts.com/3/javascriptcharts/ChartScrollbar#updateOnReleaseOnly

Alternatively, you can setup generic JavaScript `mousedown` and `mouseup` events. Just ignore `zoomed` event if the mouse is down.

Here's an example:

https://codepen.io/team/amcharts/pen/2466eefebdfecfcc77a0b2b17cb3efd4?editors=0010

I hope the code in there makes sense.

**Comment by coderkeku** [comment]
@martynasma This would work, thanks.

**Comment by martynasma** [comment]
You're welcome!
