### ISSUE TITLE
"save as" does not limit the data to zoomed data

### ISSUE THREAD

**Issue by coderkeku** [amcharts/amcharts3#82]
The "save as" function (CSV, XLSX) does not limit the resulting data after the sliders are used to narrow the time frame. where as the function "download as" (PNG, JPEG) shows only the zoomed data.

**Comment by martynasma** [comment]
Hi there,

Try using `exportSelection` in export settings:

```
"export": {
  "enabled": true,
  "exportSelection": true
}
```

https://github.com/amcharts/export#complete-list-of-available-export-settings

**Comment by coderkeku** [comment]
It worked, thanks, is there any way to preserve browser timezone in exported data?

**Comment by martynasma** [comment]
It depends on how is your data structured and what format you are exporting to.

Can you share a sample of your data?

**Comment by coderkeku** [comment]
![image](https://cloud.githubusercontent.com/assets/23261693/21267286/b042c9d6-c3cf-11e6-8281-f8bba5d2e084.png)

The graph in UI is plotted in browser time zone, but data exported is in UTC time zone same as the data which was given to graph

**Comment by martynasma** [comment]
Sorry, missed your response. Our support team does not cover GitHub.

It might depend on how your dates are passed in in data. If you haven't resolved this yet, can you please share your complete chart config and data?
