### ISSUE TITLE
ChartScrollbar update using synchronisation between amStock

### ISSUE THREAD

**Issue by bthieurmel** [amcharts/amcharts3#87]
Hi,

I synchronize few amStock using ``zoomed`` listener and ``zoomToDates`` method. When changing one, the others change well but not the chartScrollbar.

Is-it a little bug or here is a solution ?

Thanks.

**Comment by martynasma** [comment]
Hi there,

Stock Chart does not have `zoomToDates()` method. (if you're calling it directly on a Stock Panel, it won't affect zoom on the whole of the chart)

So if you want to sync up several Stock Charts, you will need to use chart's [`zoom()`](http://docs.amcharts.com/3/javascriptstockchart/AmStockChart#zoom) method.

**Comment by bthieurmel** [comment]
Thanks. It's the perfect way. Sorry for don't see this before issue.

**Comment by martynasma** [comment]
No worries. Glad I could help.

Moving forward, if you hit any more issues, reach out to contact@amcharts.com. GitHub is not being monitored by support staff continuously, so it's slower.
