### ISSUE TITLE
ZoomToIndexes throwing error

### ISSUE THREAD

**Issue by melneff** [amcharts/amcharts3#88]
Hello,

Trying to do a simple zoom on a simple stacked chart, but getting an error on this line:

$scope.runsChart = AmCharts.makeChart("Runs_chart", $scope.RunsConfig, 100);

The error is this:
TypeError: this.categoryAxis.zoom is not a function

When I look at the category axis the object does not have any of the methods it should have like zoom. I create the chart in the normal way:

$scope.runsChart = AmCharts.makeChart("Runs_chart", $scope.RunsConfig, 100);

Also, the zooming works and presents the chart perfectly, but it throws this error and causes some bugs when I navigate away from the tab.

**Comment by martynasma** [comment]
Hi there,

Category axis does not have `zoom()` method. If you'd like to zoom the chart, you should use one of the chart's zoom functions:

http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#zoomToCategoryValues
http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#zoomToDates
http://docs.amcharts.com/3/javascriptcharts/AmSerialChart#zoomToIndexes

**Comment by melneff** [comment]
Yes, I am calling ZoomToIndexes and getting that error...

Anyway, I found the problem. CategoryAxis is readonly so if you set any of
its attributes in the chart configuration, it does not get created
properly. If it is created properly it will have a zoom method. The
zoomtoindexes actually calls categoryaxis's zoom method and that's why I
was getting that error.



On Wed, Dec 14, 2016 at 11:04 PM, Martynas Majeris <notifications@github.com

**Comment by martynasma** [comment]
OK then. Thanks for the write up on the issue.

I'm going to close this then. But if you have any further issues, please contact our support directly at contact@amcharts.com. It will be quicker that way.

Thanks!
