### ISSUE TITLE
Commonjs module

### ISSUE THREAD

**Issue by kjsebastian** [amcharts/amcharts3#9]
Is there a commonjs module so I can use `import AmCharts from 'amcharts3'` while using npm?

**Comment by martynasma** [comment]
To import amCharts files using npm use this:

```
npm install amcharts/amcharts3
```

I hope this helps.

**Comment by ryan-codingintrigue** [comment]
@martynasma There is no `module.exports` though from this library (as far as I can see). All this does is assign to `window.AmCharts`.

To get around this, I used webpack with the [exports-loader](https://github.com/webpack/exports-loader):

```
import amcharts from "exports?window.AmCharts!amcharts3";
import "exports?window.AmSerialChart!amcharts3/amcharts/serial";
```

**Comment by kjsebastian** [comment]
I went with highcharts in the end. It supports npm without jumping through any hoops
