### ISSUE TITLE
Publish the package to the npm registry

### ISSUE THREAD

**Issue by onigoetz** [amcharts/amcharts3#90]
Hello,

I saw that we can install the package with the command `npm install amcharts/amcharts3`
But this downloads the package from github.

As we are behind a proxy and our build environment doesn't have internet access, just an NPM registry mirror. is it possible to have a version published on the npm registry ?

Thanks in advance

**Comment by martynasma** [comment]
Hi there.

I understand the issue you are having. However, at this point we do not have immediate plans on listing our packages on npm registry.

Sorry.
