### ISSUE TITLE
Export Annotate with legend and bulletText.

### ISSUE THREAD

**Issue by SangHakLee** [amcharts/amcharts3#91]
I want to export chart image with legend and bulletText.

But, legend and bulletText Only show when mouse over DataItem.
When i clicked export button, legend and bulletText  was hidden.

How can I download chart image with legend and bulletText.

**Comment by martynasma** [comment]
You can use export's `beforeCapture` to pre-position chart cursor before export.

Here's a demo and more details:

https://www.amcharts.com/kbase/positioning-chart-cursor-export/
