### ISSUE TITLE
files hosted on `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [amcharts/amcharts3#92]
Hi, I'm from [cdnjs](https://github.com/cdnjs/cdnjs). Recently we want to add your lib to https://cdnjs.com. I want to confirm the files hosted on cdnjs (files for browser), I have sent a PR to add files to cdnjs. The files I think they can be hosted are:

```
"basePath": "amcharts",
"files": [
   "patterns/**/*",  //all files under patterns
   "**/!(examples)/!(LICENSE|index.js|*.json|*.md|*.txt|*.csv|*.png)",  //all files except files under examples folder and document files
   "*.+(js|map)" // all js and map files under amcharts folder
  ]
```

see [node-glob](https://github.com/isaacs/node-glob#glob-primer) for more details about our rules of auto-update config.

https://github.com/cdnjs/cdnjs/pull/5747

**Comment by martynasma** [comment]
Hi there. I'm not entirely sure - do we (amCharts) need to do anything on our end?

**Comment by maruilian11** [comment]
No, you don't need to do anything.
We just want to check the files we decided to add to cdnjs are right or not.
Do we miss any files for browser usage?
Or do we add the files which are not needed for browser?
Thanks!

**Comment by martynasma** [comment]
That sounds about right. I suppose you can lose the `/samples` directory as well.

I would leave ".png" images, though. There are quite a few ones used by plugins and charts itself. Such as scrollbar grips, export buttons, etc.

Also please consider adding the following two repositories as well:

https://github.com/amcharts/amstock3
https://github.com/amcharts/ammap3

Please let me know when those are in place. We may notify our users about the option.

Thanks!

**Comment by maruilian11** [comment]
Thank you! I will report to our manager about adding those two repos.
I will let you know about it as soon as we come to any conclusion.

**Comment by PeterDaveHello** [comment]
@martynasma for the other libraries, would you please open library request issue at https://github.com/cdnjs/cdnjs/ ? Thanks.

**Comment by martynasma** [comment]
@PeterDaveHello Done. Thanks!
