### ISSUE TITLE
Totally re render chart

### ISSUE THREAD

**Issue by paveleremin** [amcharts/amcharts3#94]
I have Angular 1.4 app with chart with different time intervals, and I load them on demand.
Here is the UI
![image](https://cloud.githubusercontent.com/assets/5212490/21850441/a9099ad6-d81b-11e6-91de-4f6f0b01562d.png)
Data is correct each time, but TimeInterval (date ranges) didn't change - always Jan 06. How to re render totally chart? I'm try everything: remove/add <div> node from DOM, use amChartObject.clear() and etc.

**Comment by martynasma** [comment]
Do you mean you are calling `amChartObject.clear()` then creating a new chart and it retains a some sort of previously used data skewing the scrollbar?

That sounds like a very weird behavior. Would you be able to share some kind of demo with this behavior?
