### ISSUE TITLE
changing the behaviour for switchable property in amlegend

### ISSUE THREAD

**Issue by coderkeku** [amcharts/amcharts3#95]
Currently in AmLegend there is a property called switchable if this is enabled, legend becomes clickable. When I click on legend value it becomes disabled, we need a property to change this behaviour where in only the legend value clicked will become enabled and others becoming disabled. On additional clicks on other legends enables them too.

**Comment by martynasma** [comment]
Hi there,

I'm afraid such feature is not available.

That being said, it can be implemented using legend's events and some custom code.

Here are a few ready examples for you to start with:

https://www.amcharts.com/kbase/using-legend-to-show-only-one-graph-on-click/
https://www.amcharts.com/kbase/use-legend-to-toggle-all-graphs-on-single-click/
https://www.amcharts.com/kbase/legend-item-toggle-graphs/

Let us know if you have questions.

**Comment by coderkeku** [comment]
Thanks for the response, closing the issue
