### ISSUE TITLE
Error "d[c.effect] is not a function" using CSS to set height 100% in plot div

### ISSUE THREAD

**Issue by rafakx** [amcharts/amcharts3#96]
I'm trying to set the size of the div where the chart will be plotted to 100%, so that the chart can use the value of its parent DIV and do not set height:0px. However, doing this the plugin returns a error:

`Uncaught TypeError: d[c.effect] is not a function
    at b.update (demo.bundle.js:149896)
    at b.update (demo.bundle.js:149876)
    at b.updateAnimations (demo.bundle.js:149685)
    at b.update (demo.bundle.js:149686)
    at d.update (demo.bundle.js:149555)`

My HTML:

```
<div class="chart-pie" style={{'height':height}}>
    <div class="chart-pie-content">
        <div id={id} class='pie-chart-plot'></div>
    </div>
</div>
```

Where height is a dinamic size where the chart should use as reference

My SCSS:

```
.chart-pie{
    text-align: center;
    display: flex;

    .chart-pie-content {
        width: 100%;
        
        .pie-chart-plot{
            height: 100%;
        }
    }

    .chart-pie-centered{
        align-self: center;
    }
}
```

I'm using the AmChart with React, building the app with amchart source avaliable in npm.

**Comment by martynasma** [comment]
Are you using our official React component?

https://github.com/amcharts/amcharts3-react

**Comment by rafakx** [comment]
No, we are creating a own components. We do not intend to use the official components.

**Comment by rafakx** [comment]
@martynasma The problem has solved.

I send a wrong params on animation-effect atribute, maybe is interesting a validation of these properties.

Thanks!

**Comment by martynasma** [comment]
Thanks for the update!
