### ISSUE TITLE
Showing date/times in user's local timezone?

### ISSUE THREAD

**Issue by ammgws** [amcharts/amcharts3#99]
I have data from an API that returns datetime strings in UTC. Example dataset [here](https://live.amcharts.com/xODNh/)

When plotting these data I want the datetimes to be shown in the user's local timezone, not UTC.
Is this possible using amcharts?

(I thought about writing a postProcess function that loops through the whole dataset and updates each datetime string to an adjusted datetime string or object, but it sounds like a kludge..)

**Comment by martynasma** [comment]
I know this might seem counter-intuitive but the fix would be to remove "Data date format" (or `dataDateFormat` in config) setting. When you have that set, the chart parses the string dates and creates Date objects with the hour on user's machine, hence all times display in UTC.

When you remove date formatting option, the JavaScript's native parser takes over, which will parse date using correct time-zone info.

However, better option would be to supply your dates in data as timestamps.

**Comment by ammgws** [comment]
Removing `dataDataFormat` did the trick, thank you!
Perhaps it could be mentioned in the docs for AmSerialChart/dataDateFormat or the demo charts page?
&nbsp;
&nbsp;

> However, better option would be to supply your dates in data as timestamps.

By this do you mean it is better to supply dates in epoch time rather than in ISO8601 format?
(Is it because it is less performance intensive to parse?)

**Comment by martynasma** [comment]
Sorry, your reply slipped through the cracks.

Yes, this way there's no expensive string date parsing. And some older browsers will have issues in parsing string dates.

The timestamp gets supplied directly to `Date` constructor, which works on all browsers, even ancient ones.

And timestamps are always in UTC.

**Comment by ammgws** [comment]
Cheers for the explanation. I'll have a go sometime in the near future and see if I observe any gains.

**Comment by morrow95** [comment]
"Removing `dataDataFormat` did the trick, thank you!"

Can you explain this in a little more detail?  I am having the same issue.  I am passing UTC, but when the chart shows it is always converted to the computer's timezone.  I would prefer passing the data how it is, or in a timezone of my choosing even, not changing my data at all.

**Comment by ammgws** [comment]
Check out the example graph [here](https://live.amcharts.com/xODNh/edit/).
The dataset has three datetimes, given in UTC, and the graph is also in UTC.
However if you remove the `dataDataFormat` parameter from the code, the graph will now show in your local time instead of UTC.

The line you should remove:
![image](https://user-images.githubusercontent.com/20397027/40710779-8f590328-6434-11e8-8723-f2b3577676ea.png)
